#!/usr/bin/env python3
"""Generate native firmware fixture packets from the backend UDP protocol codec."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = "tools/firmware/generate_protocol_contract_fixtures.py"
CHECK_COMMAND = f"python {SCRIPT_PATH} --check"
OUTPUT = (
    ROOT
    / "firmware"
    / "esp"
    / "test"
    / "native_support"
    / "generated_protocol_contract_fixtures.h"
)

from vibesensor.adapters.udp.protocol import (  # noqa: E402
    HELLO_CAP_EXPLICIT_ACK,
    pack_ack,
    pack_ack_sync_clock,
    pack_cmd_identify,
    pack_cmd_sync_clock,
    pack_data,
    pack_data_ack,
    pack_hello,
    pack_hello_ack,
)


def _format_u8_array(data: bytes) -> str:
    return ", ".join(f"0x{byte:02x}" for byte in data)


def _format_i16_array(data: np.ndarray) -> str:
    return ", ".join(str(int(value)) for value in data.reshape(-1))


def render_header() -> str:
    hello_client_id = bytes.fromhex("a1b2c3d4e5f6")
    hello_control_port = 9123
    hello_sample_rate_hz = 800
    hello_frame_samples = 80
    hello_name = "front-left"
    hello_firmware_version = "fw-test"
    hello_queue_overflow_drops = 7
    hello_capabilities = HELLO_CAP_EXPLICIT_ACK
    hello_packet = pack_hello(
        client_id=hello_client_id,
        control_port=hello_control_port,
        sample_rate_hz=hello_sample_rate_hz,
        name=hello_name,
        frame_samples=hello_frame_samples,
        firmware_version=hello_firmware_version,
        queue_overflow_drops=hello_queue_overflow_drops,
        capabilities=hello_capabilities,
    )
    hello_ack_packet = pack_hello_ack(hello_client_id)

    data_client_id = bytes.fromhex("010203040506")
    data_seq = 17
    data_t0_us = 123_456_789
    data_samples = np.array([[1, 2, 3], [4, 5, 6], [-2, -1, 0]], dtype=np.int16)
    data_packet = pack_data(
        client_id=data_client_id,
        seq=data_seq,
        t0_us=data_t0_us,
        samples=data_samples,
    )

    cmd_client_id = bytes.fromhex("112233445566")
    identify_cmd_seq = 42
    identify_duration_ms = 1500
    identify_packet = pack_cmd_identify(
        cmd_client_id,
        cmd_seq=identify_cmd_seq,
        duration_ms=identify_duration_ms,
    )

    sync_clock_cmd_seq = 7
    sync_clock_server_time_us = 987_654_321
    sync_clock_applied_offset_us = -4_321
    sync_clock_round_trip_us = 6_789
    sync_clock_packet = pack_cmd_sync_clock(
        cmd_client_id,
        cmd_seq=sync_clock_cmd_seq,
        server_time_us=sync_clock_server_time_us,
        applied_offset_us=sync_clock_applied_offset_us,
        round_trip_us=sync_clock_round_trip_us,
    )
    sync_clock_ack_receive_us = 876_543_210
    sync_clock_ack_send_us = 876_543_654
    sync_clock_ack_packet = pack_ack_sync_clock(
        cmd_client_id,
        cmd_seq=sync_clock_cmd_seq,
        device_receive_us=sync_clock_ack_receive_us,
        device_send_us=sync_clock_ack_send_us,
    )

    ack_client_id = bytes.fromhex("aabbccddeeff")
    ack_cmd_seq = 99
    ack_status = 0
    ack_packet = pack_ack(
        ack_client_id,
        cmd_seq=ack_cmd_seq,
        status=ack_status,
    )

    data_ack_last_seq_received = 123
    data_ack_packet = pack_data_ack(
        data_client_id,
        last_seq_received=data_ack_last_seq_received,
    )

    return f"""#pragma once

// Generated by {SCRIPT_PATH}.
// Run `{CHECK_COMMAND}`
// to verify this header matches the backend Python UDP codec.

#include <array>
#include <cstddef>
#include <cstdint>

namespace vibesensor::test_support {{

constexpr std::array<uint8_t, 6> kHelloClientId = {{{_format_u8_array(hello_client_id)}}};
constexpr uint16_t kHelloControlPort = {hello_control_port};
constexpr uint16_t kHelloSampleRateHz = {hello_sample_rate_hz};
constexpr uint16_t kHelloFrameSamples = {hello_frame_samples};
constexpr char kHelloName[] = "{hello_name}";
constexpr char kHelloFirmwareVersion[] = "{hello_firmware_version}";
constexpr uint32_t kHelloQueueOverflowDrops = {hello_queue_overflow_drops};
constexpr uint8_t kHelloCapabilities = {hello_capabilities};
constexpr std::array<uint8_t, {len(hello_packet)}> kHelloPacket = {{{_format_u8_array(hello_packet)}}};
constexpr std::array<uint8_t, {len(hello_ack_packet)}> kHelloAckPacket = {{{_format_u8_array(hello_ack_packet)}}};

constexpr std::array<uint8_t, 6> kDataClientId = {{{_format_u8_array(data_client_id)}}};
constexpr uint32_t kDataSeq = {data_seq};
constexpr uint64_t kDataT0Us = {data_t0_us}ULL;
constexpr uint16_t kDataSampleCount = {data_samples.shape[0]};
constexpr std::array<int16_t, {data_samples.size}> kDataSamples = {{{_format_i16_array(data_samples)}}};
constexpr std::array<uint8_t, {len(data_packet)}> kDataPacket = {{{_format_u8_array(data_packet)}}};

constexpr std::array<uint8_t, 6> kCommandClientId = {{{_format_u8_array(cmd_client_id)}}};
constexpr uint32_t kIdentifyCmdSeq = {identify_cmd_seq};
constexpr uint16_t kIdentifyDurationMs = {identify_duration_ms};
constexpr std::array<uint8_t, {len(identify_packet)}> kIdentifyPacket = {{{_format_u8_array(identify_packet)}}};

constexpr uint32_t kSyncClockCmdSeq = {sync_clock_cmd_seq};
constexpr uint64_t kSyncClockServerTimeUs = {sync_clock_server_time_us}ULL;
constexpr int64_t kSyncClockAppliedOffsetUs = {sync_clock_applied_offset_us}LL;
constexpr uint32_t kSyncClockRoundTripUs = {sync_clock_round_trip_us};
constexpr std::array<uint8_t, {len(sync_clock_packet)}> kSyncClockPacket = {{{_format_u8_array(sync_clock_packet)}}};
constexpr uint64_t kSyncClockAckReceiveUs = {sync_clock_ack_receive_us}ULL;
constexpr uint64_t kSyncClockAckSendUs = {sync_clock_ack_send_us}ULL;
constexpr std::array<uint8_t, {len(sync_clock_ack_packet)}> kSyncClockAckPacket = {{{_format_u8_array(sync_clock_ack_packet)}}};

constexpr std::array<uint8_t, 6> kAckClientId = {{{_format_u8_array(ack_client_id)}}};
constexpr uint32_t kAckCmdSeq = {ack_cmd_seq};
constexpr uint8_t kAckStatus = {ack_status};
constexpr std::array<uint8_t, {len(ack_packet)}> kAckPacket = {{{_format_u8_array(ack_packet)}}};

constexpr uint32_t kDataAckLastSeqReceived = {data_ack_last_seq_received};
constexpr std::array<uint8_t, {len(data_ack_packet)}> kDataAckPacket = {{{_format_u8_array(data_ack_packet)}}};

}}  // namespace vibesensor::test_support
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate firmware protocol contract fixtures from the backend UDP codec."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed generated header is up to date.",
    )
    args = parser.parse_args()

    rendered = render_header()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8")
        if current != rendered:
            print(
                f"Protocol contract fixtures are out of date. Run {SCRIPT_PATH}.",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
