#!/usr/bin/env python3
"""Helpers for the main-release workflow's extracted release steps."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from urllib import error, request

_STANDARD_ESP32_APP_OFFSET = "0x10000"
_ENV_OFFSET_RE = re.compile(r"ESP32_APP_OFFSET[^0-9A-Fa-f]*(0x[0-9A-Fa-f]+)")
_GITHUB_API_BASE = "https://api.github.com"
GITHUB_API_TIMEOUT_S = 30


@dataclass(frozen=True)
class ReleaseVersionInfo:
    version: str
    tag: str
    bundle: str


@dataclass(frozen=True)
class ReleaseSummary:
    id: int
    tag: str
    title: str


def _run(
    command: list[str], *, cwd: Path | None = None, capture_output: bool = False
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=None if cwd is None else str(cwd),
        check=True,
        text=True,
        capture_output=capture_output,
    )


def _repo_root(raw_path: str | None) -> Path:
    if raw_path is not None:
        return Path(raw_path).resolve()
    return Path(__file__).resolve().parents[2]


def _release_date(now: datetime | None = None) -> str:
    current = now or datetime.now(UTC)
    return f"{current.year}.{current.month}.{current.day}"


def _git_release_tags(repo_root: Path) -> list[str]:
    result = _run(
        ["git", "tag", "-l", "server-v*"],
        cwd=repo_root,
        capture_output=True,
    )
    return [line for line in result.stdout.splitlines() if line]


def compute_release_version_info(
    repo_root: Path,
    *,
    now: datetime | None = None,
    existing_tags: list[str] | None = None,
) -> ReleaseVersionInfo:
    base_version = _release_date(now)
    prefix = f"server-v{base_version}"
    max_suffix: int | None = None
    for tag in (
        existing_tags if existing_tags is not None else _git_release_tags(repo_root)
    ):
        if not tag.startswith(prefix):
            continue
        suffix = tag[len(prefix) :]
        if suffix == "":
            candidate = 0
        elif re.fullmatch(r"\.\d+", suffix):
            candidate = int(suffix[1:])
        else:
            continue
        max_suffix = candidate if max_suffix is None else max(max_suffix, candidate)
    version = base_version if max_suffix is None else f"{base_version}.{max_suffix + 1}"
    return ReleaseVersionInfo(
        version=version,
        tag=f"server-v{version}",
        bundle=f"vibesensor-fw-v{version}.zip",
    )


def write_github_output(output_path: Path, version_info: ReleaseVersionInfo) -> None:
    with output_path.open("a", encoding="utf-8") as handle:
        handle.write(f"version={version_info.version}\n")
        handle.write(f"tag={version_info.tag}\n")
        handle.write(f"bundle={version_info.bundle}\n")


def stamp_version_file(version_file: Path, version: str) -> None:
    version_file.write_text(
        "# Auto-generated by main-release workflow - do not edit.\n"
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )


def build_server_wheel(repo_root: Path, version: str) -> Path:
    version_file = repo_root / "apps" / "server" / "vibesensor" / "_version.py"
    version_file.parent.mkdir(parents=True, exist_ok=True)
    stamp_version_file(version_file, version)
    _run(
        [sys.executable, "-m", "pip", "install", "--upgrade", "pip", "build"],
        cwd=repo_root,
    )
    _run([sys.executable, "-m", "build", "--wheel", "apps/server/"], cwd=repo_root)
    wheels = sorted((repo_root / "apps" / "server" / "dist").glob("*.whl"))
    if not wheels:
        raise SystemExit("No wheel produced under apps/server/dist.")
    return wheels[-1]


def _app_offset_from_envdump(firmware_dir: Path, env_name: str) -> str:
    try:
        stdout = _run(
            ["pio", "run", "-e", env_name, "-t", "envdump"],
            cwd=firmware_dir,
            capture_output=True,
        ).stdout
    except subprocess.CalledProcessError:
        return _STANDARD_ESP32_APP_OFFSET
    match = _ENV_OFFSET_RE.search(stdout)
    if match is None:
        return _STANDARD_ESP32_APP_OFFSET
    try:
        return hex(int(match.group(1), 16))
    except ValueError:
        return _STANDARD_ESP32_APP_OFFSET


def build_firmware_manifest(
    firmware_dir: Path,
    *,
    generated_from: str | None = None,
) -> dict[str, object]:
    dist_dir = firmware_dir / "dist"
    if not dist_dir.is_dir():
        raise SystemExit(f"Firmware dist directory does not exist: {dist_dir}")
    manifest: dict[str, object] = {
        "generated_from": generated_from or os.getenv("GITHUB_SHA", "unknown"),
        "environments": [],
    }
    env_dirs = sorted(path for path in dist_dir.iterdir() if path.is_dir())
    for env_dir in env_dirs:
        env_name = env_dir.name
        app_offset = _app_offset_from_envdump(firmware_dir, env_name)
        segments: list[dict[str, str]] = []
        for file_name, offset in (
            ("firmware.bin", app_offset),
            ("bootloader.bin", "0x1000"),
            ("partitions.bin", "0x8000"),
            ("boot_app0.bin", "0xe000"),
        ):
            artifact = env_dir / file_name
            if not artifact.exists():
                continue
            segments.append(
                {
                    "file": f"{env_name}/{file_name}",
                    "offset": offset,
                    "sha256": hashlib.sha256(artifact.read_bytes()).hexdigest(),
                }
            )
        environments = manifest["environments"]
        assert isinstance(environments, list)
        environments.append({"name": env_name, "segments": segments})
    return manifest


def write_firmware_manifest(
    firmware_dir: Path,
    *,
    generated_from: str | None = None,
) -> Path:
    manifest_path = firmware_dir / "dist" / "flash.json"
    manifest_path.write_text(
        json.dumps(
            build_firmware_manifest(firmware_dir, generated_from=generated_from),
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return manifest_path


def select_superseded_releases(
    releases: list[dict[str, object]],
    *,
    current_tag: str,
    release_title_prefix: str,
) -> list[ReleaseSummary]:
    title_prefix = f"{release_title_prefix} "
    selected: list[ReleaseSummary] = []
    for release in releases:
        release_id = release.get("id")
        if not isinstance(release_id, int):
            raise SystemExit("Release payload is missing an integer id.")
        tag = str(release.get("tag_name") or "")
        title = str(release.get("name") or "")
        if tag == current_tag or not tag.startswith("server-v"):
            continue
        if not title.startswith(title_prefix):
            continue
        selected.append(ReleaseSummary(id=release_id, tag=tag, title=title))
    return selected


def _github_token() -> str:
    token = os.getenv("GH_TOKEN") or os.getenv("GITHUB_TOKEN")
    if not token:
        raise SystemExit("GH_TOKEN or GITHUB_TOKEN must be set.")
    return token


def _github_request(method: str, repo: str, path: str) -> object | None:
    api_path = f"/repos/{repo}/{path.lstrip('/')}"
    req = request.Request(
        f"{_GITHUB_API_BASE}{api_path}",
        method=method,
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {_github_token()}",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    try:
        with request.urlopen(req, timeout=GITHUB_API_TIMEOUT_S) as response:
            payload = response.read().decode("utf-8")
    except error.HTTPError:
        raise
    except TimeoutError as exc:
        raise SystemExit(
            f"GitHub API {method} {api_path} timed out after {GITHUB_API_TIMEOUT_S}s."
        ) from exc
    except error.URLError as exc:
        raise SystemExit(
            f"GitHub API {method} {api_path} failed: {exc.reason}"
        ) from exc
    if not payload:
        return None
    return json.loads(payload)


def _list_releases(repo: str) -> list[dict[str, object]]:
    releases: list[dict[str, object]] = []
    page = 1
    while True:
        payload = _github_request("GET", repo, f"releases?per_page=100&page={page}")
        if not isinstance(payload, list):
            raise SystemExit("Unexpected GitHub releases payload shape.")
        if not payload:
            break
        releases.extend(payload)
        if len(payload) < 100:
            break
        page += 1
    return releases


def cleanup_superseded_releases(
    repo: str,
    *,
    current_tag: str,
    release_title_prefix: str,
) -> list[ReleaseSummary]:
    removed = select_superseded_releases(
        _list_releases(repo),
        current_tag=current_tag,
        release_title_prefix=release_title_prefix,
    )
    for release in removed:
        print(f"Deleting superseded Wheel / ESP release {release.tag}", flush=True)
        _github_request("DELETE", repo, f"releases/{release.id}")
        try:
            _github_request("DELETE", repo, f"git/refs/tags/{release.tag}")
        except error.HTTPError as exc:
            if exc.code != 404:
                raise
            print(f"Tag {release.tag} was already absent", flush=True)
    return removed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Extracted helper commands for the main-release workflow."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    compute_parser = subparsers.add_parser("compute-version")
    compute_parser.add_argument("--repo-root", default=None)
    compute_parser.add_argument("--github-output", default=None)

    wheel_parser = subparsers.add_parser("build-wheel")
    wheel_parser.add_argument("--repo-root", default=None)
    wheel_parser.add_argument("--version", required=True)

    manifest_parser = subparsers.add_parser("generate-firmware-manifest")
    manifest_parser.add_argument("--firmware-dir", required=True)
    manifest_parser.add_argument("--generated-from", default=None)

    cleanup_parser = subparsers.add_parser("cleanup-releases")
    cleanup_parser.add_argument("--repo", required=True)
    cleanup_parser.add_argument("--current-tag", required=True)
    cleanup_parser.add_argument(
        "--release-title-prefix",
        default="Wheel / ESP release",
    )
    cleanup_parser.add_argument("--dry-run", action="store_true")

    args = parser.parse_args(argv)
    if args.command == "compute-version":
        version_info = compute_release_version_info(_repo_root(args.repo_root))
        if args.github_output:
            write_github_output(Path(args.github_output), version_info)
        else:
            print(json.dumps(asdict(version_info), indent=2))
        return 0

    if args.command == "build-wheel":
        wheel_path = build_server_wheel(_repo_root(args.repo_root), args.version)
        print(wheel_path, flush=True)
        return 0

    if args.command == "generate-firmware-manifest":
        manifest_path = write_firmware_manifest(
            Path(args.firmware_dir).resolve(),
            generated_from=args.generated_from,
        )
        print(manifest_path, flush=True)
        return 0

    selected = select_superseded_releases(
        _list_releases(args.repo),
        current_tag=args.current_tag,
        release_title_prefix=args.release_title_prefix,
    )
    if args.dry_run:
        print(json.dumps([asdict(release) for release in selected], indent=2))
        return 0
    cleanup_superseded_releases(
        args.repo,
        current_tag=args.current_tag,
        release_title_prefix=args.release_title_prefix,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
