compute_ui_hash() {
  (
    cd "${REPO_ROOT}" || exit
    git ls-files \
      apps/ui \
      tools/config/sync_shared_contracts_to_ui.mjs \
      | LC_ALL=C sort \
      | xargs sha256sum \
      | sha256sum \
      | awk '{print $1}'
  )
}

sync_dir_contents() {
  local source_dir="$1"
  local target_dir="$2"

  mkdir -p "${target_dir}"
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "${source_dir}/" "${target_dir}/"
    return
  fi

  find "${target_dir}" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
  cp -a "${source_dir}/." "${target_dir}/"
}

build_ui_bundle() {
  local ui_dir="${REPO_ROOT}/apps/ui"
  local server_static_dir="${REPO_ROOT}/apps/server/vibesensor/static"
  local should_build="1"
  local current_hash=""
  local previous_hash=""

  if [ "${FORCE_UI_BUILD}" != "1" ] && [ -d "${ui_dir}/dist" ]; then
    current_hash="$(compute_ui_hash || true)"
    if [ -f "${UI_HASH_FILE}" ]; then
      previous_hash="$(cat "${UI_HASH_FILE}")"
    fi
    if [ -n "${current_hash}" ] && [ "${current_hash}" = "${previous_hash}" ]; then
      should_build="0"
      echo "UI sources unchanged; skipping npm run build"
    fi
  fi

  if [ ! -d "${ui_dir}/node_modules" ]; then
    echo "UI dependencies missing; running npm ci in apps/ui"
    (cd "${ui_dir}" && npm ci)
  fi

  if [ "${should_build}" = "1" ]; then
    echo "Syncing generated UI contracts"
    (cd "${ui_dir}" && npm run sync:generated-contracts)
    echo "Building UI bundle"
    (cd "${ui_dir}" && npm run build)
    if [ -z "${current_hash}" ]; then
      current_hash="$(compute_ui_hash || true)"
    fi
    if [ -n "${current_hash}" ]; then
      printf '%s\n' "${current_hash}" >"${UI_HASH_FILE}"
    fi
  fi

  echo "Syncing UI bundle into apps/server/vibesensor/static"
  sync_dir_contents "${ui_dir}/dist" "${server_static_dir}"
}

compute_app_build_version() {
  local release_tag=""
  local git_sha=""
  local build_stamp=""

  release_tag="$(
    git -C "${REPO_ROOT}" tag -l "server-v*" --points-at HEAD 2>/dev/null \
      | sort -V \
      | tail -n 1
  )"
  if [ -n "${release_tag}" ]; then
    printf '%s\n' "${release_tag#server-v}"
    return
  fi

  git_sha="$(git -C "${REPO_ROOT}" rev-parse --short=12 HEAD 2>/dev/null || true)"
  if [ -n "${git_sha}" ]; then
    printf '0.0.0.dev0+g%s\n' "${git_sha}"
    return
  fi

  build_stamp="$(date -u +%Y%m%d%H%M%S)"
  printf '0.0.0.dev0+build.%s\n' "${build_stamp}"
}

stamp_app_version_file() {
  local version_file="$1"
  local version="$2"

  cat >"${version_file}" <<EOF_INNER
# Auto-generated by pi-gen app artifact build - do not edit.
__version__ = "${version}"
EOF_INNER
}

build_app_artifacts() {
  local build_root=""
  local app_version=""
  local wheel_path=""

  echo "Preparing app artifacts..."
  build_ui_bundle

  rm -rf "${APP_ARTIFACT_DIR}"
  mkdir -p "${APP_WHEEL_DIR}" "${APP_PUBLIC_DIR}"
  sync_dir_contents "${REPO_ROOT}/apps/server/vibesensor/static" "${APP_PUBLIC_DIR}"

  build_root="$(mktemp -d -p "${CACHE_DIR}" app-build-XXXXXX)"
  mkdir -p "${build_root}/apps"
  rsync -a --delete \
    "${REPO_ROOT}/apps/server/" "${build_root}/apps/server/"
  app_version="$(compute_app_build_version)"
  echo "Stamping app wheel version: ${app_version}"
  stamp_app_version_file "${build_root}/apps/server/vibesensor/_version.py" "${app_version}"

  rm -rf "${build_root}/apps/server/vibesensor/static"
  sync_dir_contents "${APP_PUBLIC_DIR}" "${build_root}/apps/server/vibesensor/static"

  (
    cd "${build_root}" || exit
    "${VS_PYTHON_BIN}" -m venv .build-venv
    ./.build-venv/bin/pip install --upgrade pip build >/dev/null
    ./.build-venv/bin/python -m build --wheel apps/server
  )

  wheel_path="$(find "${build_root}/apps/server/dist" -maxdepth 1 -type f -name 'vibesensor-*.whl' | sort -V | tail -n 1)"
  if [ -z "${wheel_path}" ]; then
    echo "Failed to build vibesensor wheel artifact."
    rm -rf "${build_root}"
    exit 1
  fi
  cp -f "${wheel_path}" "${APP_WHEEL_DIR}/"
  APP_WHEEL_PATH="${APP_WHEEL_DIR}/$(basename "${wheel_path}")"
  # shellcheck disable=SC2034  # Consumed by stage_assembly.sh after this library is sourced.
  APP_WHEEL_FILE="$(basename "${APP_WHEEL_PATH}")"

  {
    echo "build_mode=app"
    echo "generated_at_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "version=${app_version}"
    echo "wheel=$(basename "${wheel_path}")"
    echo "wheel_sha256=$(sha256sum "${APP_WHEEL_PATH}" | awk '{print $1}')"
  } >"${APP_ARTIFACT_DIR}/manifest.txt"

  rm -rf "${build_root}"
  echo "App artifacts ready in: ${APP_ARTIFACT_DIR}"
}

require_prebuilt_app_artifacts() {
  APP_WHEEL_PATH="$(find "${APP_WHEEL_DIR}" -maxdepth 1 -type f -name 'vibesensor-*.whl' | sort -V | tail -n 1)"
  if [ -z "${APP_WHEEL_PATH}" ]; then
    echo "Missing app wheel artifact in ${APP_WHEEL_DIR}."
    echo "Run BUILD_MODE=app ./infra/pi-image/pi-gen/build.sh first."
    exit 1
  fi
  # shellcheck disable=SC2034  # Consumed by stage_assembly.sh after this library is sourced.
  APP_WHEEL_FILE="$(basename "${APP_WHEEL_PATH}")"
  if [ ! -f "${APP_PUBLIC_DIR}/index.html" ]; then
    echo "Missing prebuilt UI assets in ${APP_PUBLIC_DIR}."
    echo "Run BUILD_MODE=app ./infra/pi-image/pi-gen/build.sh first."
    exit 1
  fi
}
