from __future__ import annotations

from test_support.core import (
    ADDITIONAL_CAR_PROFILES,
    ALL_WHEEL_SENSORS,
    CAR_PROFILES,
    NON_WHEEL_SENSORS,
    SENSOR_DRIVER_SEAT,
    SENSOR_ENGINE,
    SENSOR_FL,
    SENSOR_FR,
    SENSOR_FRONT_SUBFRAME,
    SENSOR_PASSENGER_SEAT,
    SENSOR_REAR_SUBFRAME,
    SENSOR_RL,
    SENSOR_RR,
    SENSOR_TRUNK,
    SPEED_HIGH,
    SPEED_LOW,
    SPEED_MID,
)

# Shared direct-injection multi-sensor matrix catalogs.
OPTIMIZED_DIAGNOSTIC_PROFILES = [CAR_PROFILES[0], CAR_PROFILES[2], CAR_PROFILES[-1]]
OPTIMIZED_DIAGNOSTIC_PROFILE_IDS = [profile["name"] for profile in OPTIMIZED_DIAGNOSTIC_PROFILES]
DIAGNOSTIC_OPTIMIZED_PROFILES = OPTIMIZED_DIAGNOSTIC_PROFILES
DIAGNOSTIC_OPTIMIZED_PROFILE_IDS = OPTIMIZED_DIAGNOSTIC_PROFILE_IDS
DIAGNOSTIC_WHEEL_CORNERS = ["FL", "FR", "RL", "RR"]
DIAGNOSTIC_STANDARD_SPEEDS = [SPEED_LOW, SPEED_MID, SPEED_HIGH]
DIAGNOSTIC_STANDARD_SPEED_IDS = ["low", "mid", "high"]
DIAGNOSTIC_2_SENSOR_FL_RR = [SENSOR_FL, SENSOR_RR]
DIAGNOSTIC_2_SENSOR_FR_RL = [SENSOR_FR, SENSOR_RL]
DIAGNOSTIC_4_SENSOR_SET = ALL_WHEEL_SENSORS[:]
DIAGNOSTIC_8_SENSOR_SET = ALL_WHEEL_SENSORS + NON_WHEEL_SENSORS[:4]
DIAGNOSTIC_12_SENSOR_SET = ALL_WHEEL_SENSORS + NON_WHEEL_SENSORS[:8]
DIAGNOSTIC_TWO_SENSOR_LOCALIZATION_CASES = [
    ("FL_in_FL_RR", DIAGNOSTIC_2_SENSOR_FL_RR, "FL"),
    ("RR_in_FL_RR", DIAGNOSTIC_2_SENSOR_FL_RR, "RR"),
    ("FR_in_FR_RL", DIAGNOSTIC_2_SENSOR_FR_RL, "FR"),
    ("RL_in_FR_RL", DIAGNOSTIC_2_SENSOR_FR_RL, "RL"),
]
DIAGNOSTIC_MULTI_SENSOR_LEVEL_CASES = [
    ("8s", DIAGNOSTIC_8_SENSOR_SET, "8s"),
    ("12s", DIAGNOSTIC_12_SENSOR_SET, "12s"),
]
DIAGNOSTIC_MULTI_SENSOR_BASELINE_CASES = [
    ("8s", DIAGNOSTIC_8_SENSOR_SET, "8sensor"),
    ("12s", DIAGNOSTIC_12_SENSOR_SET, "12sensor"),
]
DIAGNOSTIC_MULTI_SENSOR_DIFFUSE_CASES = [
    ("8s_diffuse", DIAGNOSTIC_8_SENSOR_SET, "8s"),
    ("12s_diffuse", DIAGNOSTIC_12_SENSOR_SET, "12s"),
]
DIAGNOSTIC_PHASED_CORNERS = ["FL", "RR"]
DIAGNOSTIC_SPEED_SWEEP_CORNERS = ["FR", "RL"]
DIAGNOSTIC_WEAK_SIGNAL_CORNERS = ["FL", "RR"]
DIAGNOSTIC_AMPLITUDE_SWEEP_CASES = [
    (0.03, 18.0, "amp=0.03"),
    (0.06, 26.0, "amp=0.06"),
    (0.12, 34.0, "amp=0.12"),
]
TRANSIENT_VERY_HIGH_SPEED_CORNERS = ["FR", "RL"]
TRANSIENT_NO_FAULT_SPEED_CASES = [
    ("low", SPEED_LOW),
    ("high", SPEED_HIGH),
]
TRANSIENT_SPEED_SWEEP_CORNERS = ["FL", "RL"]

# Weird-sensor-mix catalogs.
WEIRD_CABIN_SENSOR_MIXES = [
    ("seat+trunk", [SENSOR_DRIVER_SEAT, SENSOR_TRUNK]),
    ("seat+pass", [SENSOR_DRIVER_SEAT, SENSOR_PASSENGER_SEAT]),
    ("pass+trunk", [SENSOR_PASSENGER_SEAT, SENSOR_TRUNK]),
    ("all-cabin", [SENSOR_DRIVER_SEAT, SENSOR_PASSENGER_SEAT, SENSOR_TRUNK]),
    ("seat-only", [SENSOR_DRIVER_SEAT]),
]
WEIRD_CABIN_SENSOR_MIX_IDS = [mix[0] for mix in WEIRD_CABIN_SENSOR_MIXES]
WEIRD_SPEED_CASES = [
    ("30kph", 30.0),
    ("80kph", 80.0),
    ("120kph", 120.0),
]
WEIRD_SPEEDS = [speed for _, speed in WEIRD_SPEED_CASES]
WEIRD_SPEED_IDS = [case_id for case_id, _ in WEIRD_SPEED_CASES]
WEIRD_WHEEL_CORNER_CASES = [
    ("FL", SENSOR_FL),
    ("FR", SENSOR_FR),
    ("RL", SENSOR_RL),
    ("RR", SENSOR_RR),
]
WEIRD_CABIN_WHEEL_COMBOS = [
    ("seat+trunk", [SENSOR_DRIVER_SEAT, SENSOR_TRUNK]),
    ("pass", [SENSOR_PASSENGER_SEAT]),
    ("all-cabin", [SENSOR_DRIVER_SEAT, SENSOR_PASSENGER_SEAT, SENSOR_TRUNK]),
]
WEIRD_ASYMMETRIC_COMBOS = [
    ("front-heavy", [SENSOR_DRIVER_SEAT, SENSOR_PASSENGER_SEAT]),
    ("rear-heavy", [SENSOR_TRUNK, SENSOR_REAR_SUBFRAME]),
    ("mixed-fr", [SENSOR_DRIVER_SEAT, SENSOR_TRUNK]),
    ("cross-region", [SENSOR_DRIVER_SEAT, SENSOR_REAR_SUBFRAME]),
]
WEIRD_SPARSE_SENSOR_CASES = [
    ("seat", SENSOR_DRIVER_SEAT),
    ("pass", SENSOR_PASSENGER_SEAT),
    ("trunk", SENSOR_TRUNK),
    ("engine", SENSOR_ENGINE),
    ("front-sub", SENSOR_FRONT_SUBFRAME),
    ("rear-sub", SENSOR_REAR_SUBFRAME),
]
WEIRD_TOPOLOGY_PROFILES = [CAR_PROFILES[2], *ADDITIONAL_CAR_PROFILES]
WEIRD_TOPOLOGY_PROFILE_IDS = [profile["name"] for profile in WEIRD_TOPOLOGY_PROFILES]
WEIRD_WEAK_AMPLITUDE_CASES = [
    ("low", 0.02, 16.0),
    ("med", 0.04, 20.0),
]
WEIRD_HIGH_TRANSFER_CASES = [
    ("tf0.7", 0.7),
    ("tf0.9", 0.9),
]
WEIRD_SPARSE_SPEED_CASES = [
    ("60kph", 60.0),
    ("100kph", 100.0),
]
WEIRD_SPARSE_SPEEDS = [speed for _, speed in WEIRD_SPARSE_SPEED_CASES]
WEIRD_SPARSE_SPEED_IDS = [case_id for case_id, _ in WEIRD_SPARSE_SPEED_CASES]
WEIRD_PHASED_SCENARIOS = [
    ("seat+trunk@60", [SENSOR_DRIVER_SEAT, SENSOR_TRUNK], 60.0),
    ("seat+pass@80", [SENSOR_DRIVER_SEAT, SENSOR_PASSENGER_SEAT], 80.0),
    ("pass+trunk@100", [SENSOR_PASSENGER_SEAT, SENSOR_TRUNK], 100.0),
    ("all-cabin@80", [SENSOR_DRIVER_SEAT, SENSOR_PASSENGER_SEAT, SENSOR_TRUNK], 80.0),
    ("seat-only@60", [SENSOR_DRIVER_SEAT], 60.0),
    ("seat+rear-sub@80", [SENSOR_DRIVER_SEAT, SENSOR_REAR_SUBFRAME], 80.0),
    ("trunk+front-sub@100", [SENSOR_TRUNK, SENSOR_FRONT_SUBFRAME], 100.0),
]
WEIRD_CONTRADICTORY_MIXES = [
    ("seat+trunk", [SENSOR_DRIVER_SEAT, SENSOR_TRUNK]),
    ("seat+pass", [SENSOR_DRIVER_SEAT, SENSOR_PASSENGER_SEAT]),
    ("pass+trunk", [SENSOR_PASSENGER_SEAT, SENSOR_TRUNK]),
    ("all-cabin", [SENSOR_DRIVER_SEAT, SENSOR_PASSENGER_SEAT, SENSOR_TRUNK]),
    ("seat+rear-sub", [SENSOR_DRIVER_SEAT, SENSOR_REAR_SUBFRAME]),
]
WEIRD_NOISE_LEVEL_CASES = [
    ("moderate", 0.03, 20.0),
    ("heavy", 0.05, 24.0),
]
WEIRD_STRONG_AMPLITUDE_CASES = [
    ("amp0.04", 0.04, 20.0),
    ("amp0.06", 0.06, 24.0),
    ("amp0.08", 0.08, 28.0),
    ("amp0.10", 0.10, 30.0),
    ("amp0.12", 0.12, 32.0),
]
WEIRD_RESOLVE_COMBOS = [
    ("seat+trunk", [SENSOR_DRIVER_SEAT, SENSOR_TRUNK]),
    ("all-cabin", [SENSOR_DRIVER_SEAT, SENSOR_PASSENGER_SEAT, SENSOR_TRUNK]),
]
WEIRD_GRANULARITY_SCENARIOS = [
    ("sparse-cabin", [SENSOR_DRIVER_SEAT, SENSOR_TRUNK], 80.0),
    ("dense-cabin", [SENSOR_DRIVER_SEAT, SENSOR_PASSENGER_SEAT, SENSOR_TRUNK], 80.0),
]

# Messy real-world catalogs.
MESSY_POTHOLE_SPEED_CASES = [
    ("mid", SPEED_MID),
    ("high", SPEED_HIGH),
]
MESSY_OVERLAP_SPEED_CASES = [
    ("60kmh", 60.0),
    ("100kmh", 100.0),
]
MESSY_DUAL_FAULT_CASES = [
    ("FL_RR", (SENSOR_FL, SENSOR_RR), SENSOR_FL),
    ("FR_RL", (SENSOR_FR, SENSOR_RL), SENSOR_FR),
]
MESSY_OUT_OF_ORDER_CORNERS = ["FL", "RR"]
MESSY_CLOCK_SKEW_CORNERS = ["FR", "RL"]
MESSY_GAIN_MISMATCH_CORNERS = ["FL", "RL"]
MESSY_AMPLITUDE_SWEEP_CASES = [
    (0.02, 16.0, "amp=0.02"),
    (0.04, 20.0, "amp=0.04"),
    (0.06, 26.0, "amp=0.06"),
    (0.09, 30.0, "amp=0.09"),
    (0.12, 34.0, "amp=0.12"),
]
MESSY_SELF_DROPOUT_CORNERS = ["FL", "RR"]
MESSY_CABIN_OVERLAP_MIXES = [
    ("driver-only", [SENSOR_DRIVER_SEAT]),
    ("seat+trunk", [SENSOR_DRIVER_SEAT, SENSOR_TRUNK]),
]
