from __future__ import annotations

from test_support.whole_run_diagnosis_builder_primitives import (
    context_interval as _context_interval,
)
from test_support.whole_run_diagnosis_builder_primitives import (
    diagnosis_finding as _finding,
)
from test_support.whole_run_diagnosis_builder_primitives import (
    order_summary as _order_summary,
)
from test_support.whole_run_diagnosis_builder_primitives import (
    spatial_summary as _spatial_summary,
)
from test_support.whole_run_diagnosis_scenario_types import WholeRunDiagnosisScenario
from vibesensor.domain import DrivingPhase


def whole_run_diagnosis_scenarios() -> tuple[WholeRunDiagnosisScenario, ...]:
    return (
        _clear_wheel_scenario(),
        _counterevidence_overturn_scenario(),
        _ambiguous_matching_source_scenario(),
    )


def _clear_wheel_scenario() -> WholeRunDiagnosisScenario:
    wheel = _finding(
        finding_id="F_CLEAR_WHEEL",
        suspected_source="wheel/tire",
        confidence=0.82,
        strongest_location="Front Left",
        strongest_speed_band="60-80 km/h",
        dominant_phase="cruise",
        matched_hz=13.2,
    )
    driveline = _finding(
        finding_id="F_CLEAR_DRIVELINE",
        suspected_source="driveline",
        confidence=0.70,
        strongest_location="Rear Left",
        strongest_speed_band="60-80 km/h",
        dominant_phase="cruise",
        matched_hz=26.4,
    )
    return WholeRunDiagnosisScenario(
        case_id="clear-wheel",
        analysis_metadata={
            "raw_backed_sample_count": 96,
            "raw_capture_mode": "raw_backed",
            "whole_run_context_available": True,
        },
        context_intervals=(_context_interval(),),
        order_summaries=(
            _order_summary(
                hypothesis_key="wheel_1x",
                suspected_source="wheel/tire",
                order_family="wheel",
                order_label="1x wheel",
                matched_window_count=7,
                support_ratio=0.88,
                reference_coverage_ratio=1.0,
                longest_contiguous_support_window_count=6,
                contiguous_support_ratio=0.75,
                stable_frequency_min_hz=13.1,
                stable_frequency_max_hz=13.4,
                dominant_phase="cruise",
                dominant_speed_band="60-80 km/h",
                strongest_location="front-left",
                mean_relative_error=0.02,
                drift_score=0.06,
                lock_score=0.9,
                peak_intensity_db=19.5,
                mean_vibration_strength_db=10.8,
                ref_sources=("speed+tire",),
            ),
            _order_summary(
                hypothesis_key="driveline_1x",
                suspected_source="driveline",
                order_family="driveline",
                order_label="1x driveshaft",
                matched_window_count=2,
                support_ratio=0.25,
                reference_coverage_ratio=0.75,
                longest_contiguous_support_window_count=1,
                contiguous_support_ratio=0.12,
                stable_frequency_min_hz=26.1,
                stable_frequency_max_hz=26.4,
                dominant_phase="cruise",
                dominant_speed_band="60-80 km/h",
                strongest_location="rear-left",
                mean_relative_error=0.07,
                drift_score=0.22,
                lock_score=0.5,
                peak_intensity_db=12.5,
                mean_vibration_strength_db=7.5,
                ref_sources=("speed+driveshaft",),
            ),
        ),
        spatial_summaries=(
            _spatial_summary(
                candidate_key="wheel_1x",
                suspected_source="wheel/tire",
                dominant_location="front-left",
                runner_up_location="front-right",
                supporting_window_count=7,
                supporting_sensor_count=2,
                coherent_window_count=6,
                coherence_ratio=0.86,
                location_separation_db=3.6,
                dominance_ratio=1.55,
            ),
            _spatial_summary(
                candidate_key="driveline_1x",
                suspected_source="driveline",
                dominant_location="rear-left",
                runner_up_location="rear-right",
                supporting_window_count=2,
                supporting_sensor_count=2,
                coherent_window_count=1,
                coherence_ratio=0.5,
                location_separation_db=1.2,
                dominance_ratio=1.02,
                ambiguous_location=True,
                weak_spatial_separation=True,
            ),
        ),
        findings=(wheel, driveline),
        top_causes=(wheel, driveline),
        expected_ranked_sources=("wheel/tire", "driveline"),
        expected_report_source="Wheel / Tire",
        expected_report_alternative="Driveline",
        expected_report_location="Front-Left",
        expected_report_frequency_fragment="13.1",
        expected_primary_ambiguous=False,
        expected_primary_suspicious=False,
        expected_primary_counterevidence_keys=(),
        expected_runner_up_counterevidence_keys=("weak_spatial", "incomplete_reference"),
    )


def _counterevidence_overturn_scenario() -> WholeRunDiagnosisScenario:
    wheel = _finding(
        finding_id="F_COUNTER_WHEEL",
        suspected_source="wheel/tire",
        confidence=0.84,
        strongest_location="Front Left",
        strongest_speed_band="50-70 km/h",
        dominant_phase="accel",
        matched_hz=15.0,
    )
    engine = _finding(
        finding_id="F_COUNTER_ENGINE",
        suspected_source="engine",
        confidence=0.73,
        strongest_location="Front Right",
        strongest_speed_band="50-70 km/h",
        dominant_phase="accel",
        matched_hz=22.5,
    )
    return WholeRunDiagnosisScenario(
        case_id="counterevidence-overturn",
        analysis_metadata={
            "raw_backed_sample_count": 64,
            "raw_capture_mode": "raw_backed",
            "whole_run_context_available": True,
            "whole_run_context_missing_speed_window_count": 1,
            "whole_run_context_stale_speed_window_count": 1,
            "whole_run_context_missing_rpm_window_count": 0,
            "whole_run_context_stale_rpm_window_count": 1,
        },
        context_intervals=(
            _context_interval(
                phase=DrivingPhase.ACCELERATION,
                load_state="pulling",
                speed_band="50-70 km/h",
                full_window_count=5,
                partial_window_count=2,
                missing_window_count=1,
            ),
        ),
        order_summaries=(
            _order_summary(
                hypothesis_key="wheel_1x",
                suspected_source="wheel/tire",
                order_family="wheel",
                order_label="1x wheel",
                matched_window_count=6,
                support_ratio=0.75,
                reference_coverage_ratio=0.55,
                longest_contiguous_support_window_count=2,
                contiguous_support_ratio=0.25,
                stable_frequency_min_hz=14.8,
                stable_frequency_max_hz=15.4,
                dominant_phase="accel",
                dominant_speed_band="50-70 km/h",
                strongest_location="front-left",
                mean_relative_error=0.08,
                drift_score=0.32,
                lock_score=0.42,
                peak_intensity_db=18.0,
                mean_vibration_strength_db=11.0,
                ref_sources=("speed+tire",),
            ),
            _order_summary(
                hypothesis_key="engine_2x",
                suspected_source="engine",
                order_family="engine",
                order_label="2x engine",
                matched_window_count=5,
                support_ratio=0.62,
                reference_coverage_ratio=0.92,
                longest_contiguous_support_window_count=4,
                contiguous_support_ratio=0.5,
                stable_frequency_min_hz=22.4,
                stable_frequency_max_hz=22.7,
                dominant_phase="accel",
                dominant_speed_band="50-70 km/h",
                strongest_location="front-right",
                mean_relative_error=0.03,
                drift_score=0.1,
                lock_score=0.81,
                peak_intensity_db=16.5,
                mean_vibration_strength_db=9.6,
                ref_sources=("speed+engine",),
            ),
        ),
        spatial_summaries=(
            _spatial_summary(
                candidate_key="wheel_1x",
                suspected_source="wheel/tire",
                dominant_location="front-left",
                runner_up_location="rear-left",
                supporting_window_count=6,
                supporting_sensor_count=2,
                coherent_window_count=2,
                coherence_ratio=0.33,
                location_separation_db=0.7,
                dominance_ratio=1.04,
                ambiguous_location=True,
                weak_spatial_separation=True,
            ),
            _spatial_summary(
                candidate_key="engine_2x",
                suspected_source="engine",
                dominant_location="front-right",
                runner_up_location="rear-right",
                supporting_window_count=5,
                supporting_sensor_count=2,
                coherent_window_count=4,
                coherence_ratio=0.8,
                location_separation_db=2.8,
                dominance_ratio=1.35,
            ),
        ),
        findings=(wheel, engine),
        top_causes=(wheel, engine),
        expected_ranked_sources=("engine", "wheel/tire"),
        expected_report_source="Engine",
        expected_report_alternative="Wheel / Tire",
        expected_report_location="Front-Right",
        expected_report_frequency_fragment="22.4",
        expected_primary_ambiguous=False,
        expected_primary_suspicious=False,
        expected_primary_counterevidence_keys=(
            "speed_context_gaps",
            "rpm_context_gaps",
            "incomplete_reference",
        ),
        expected_runner_up_counterevidence_keys=(
            "weak_spatial",
            "speed_context_gaps",
            "rpm_context_gaps",
        ),
    )


def _ambiguous_matching_source_scenario() -> WholeRunDiagnosisScenario:
    wheel = _finding(
        finding_id="F_AMBIG_WHEEL",
        suspected_source="wheel/tire",
        confidence=0.80,
        strongest_location="Front Left",
        strongest_speed_band="100-110 km/h",
        dominant_phase="cruise",
        matched_hz=12.9,
    )
    driveline = _finding(
        finding_id="F_AMBIG_DRIVELINE",
        suspected_source="driveline",
        confidence=0.74,
        strongest_location="Front Left",
        strongest_speed_band="100-110 km/h",
        dominant_phase="cruise",
        matched_hz=39.8,
    )
    engine = _finding(
        finding_id="F_AMBIG_ENGINE",
        suspected_source="engine",
        confidence=0.72,
        strongest_location="Front Left",
        strongest_speed_band="100-110 km/h",
        dominant_phase="cruise",
        matched_hz=51.2,
    )
    return WholeRunDiagnosisScenario(
        case_id="ambiguous-matching-source",
        analysis_metadata={
            "raw_backed_sample_count": 84,
            "raw_capture_mode": "raw_backed",
            "whole_run_context_available": True,
        },
        context_intervals=(_context_interval(speed_band="100-110 km/h"),),
        order_summaries=(
            _order_summary(
                hypothesis_key="driveshaft",
                suspected_source="driveline",
                order_family="driveline",
                order_label="1x driveshaft",
                matched_window_count=5,
                support_ratio=0.62,
                reference_coverage_ratio=0.9,
                longest_contiguous_support_window_count=3,
                contiguous_support_ratio=0.38,
                stable_frequency_min_hz=39.8,
                stable_frequency_max_hz=39.8,
                dominant_phase="cruise",
                dominant_speed_band="100-110 km/h",
                strongest_location="front-left",
                mean_relative_error=0.03,
                drift_score=0.1,
                lock_score=0.82,
                peak_intensity_db=18.0,
                mean_vibration_strength_db=10.0,
                ref_sources=("speed+driveshaft",),
            ),
            _order_summary(
                hypothesis_key="engine",
                suspected_source="engine",
                order_family="engine",
                order_label="2x engine",
                matched_window_count=5,
                support_ratio=0.62,
                reference_coverage_ratio=0.9,
                longest_contiguous_support_window_count=3,
                contiguous_support_ratio=0.38,
                stable_frequency_min_hz=51.2,
                stable_frequency_max_hz=51.2,
                dominant_phase="cruise",
                dominant_speed_band="100-110 km/h",
                strongest_location="front-left",
                mean_relative_error=0.03,
                drift_score=0.1,
                lock_score=0.82,
                peak_intensity_db=18.0,
                mean_vibration_strength_db=10.0,
                ref_sources=("speed+engine",),
            ),
            _order_summary(
                hypothesis_key="wheel",
                suspected_source="wheel/tire",
                order_family="wheel",
                order_label="1x wheel",
                matched_window_count=5,
                support_ratio=0.62,
                reference_coverage_ratio=0.9,
                longest_contiguous_support_window_count=3,
                contiguous_support_ratio=0.38,
                stable_frequency_min_hz=12.9,
                stable_frequency_max_hz=12.9,
                dominant_phase="cruise",
                dominant_speed_band="100-110 km/h",
                strongest_location="front-left",
                mean_relative_error=0.03,
                drift_score=0.1,
                lock_score=0.82,
                peak_intensity_db=18.0,
                mean_vibration_strength_db=10.0,
                ref_sources=("speed+tire",),
            ),
        ),
        spatial_summaries=(
            _spatial_summary(
                candidate_key="driveshaft",
                suspected_source="driveline",
                dominant_location="front-left",
                runner_up_location="rear-left",
                supporting_window_count=5,
                supporting_sensor_count=3,
                coherent_window_count=4,
                coherence_ratio=0.8,
                location_separation_db=2.4,
                dominance_ratio=1.2,
            ),
            _spatial_summary(
                candidate_key="engine",
                suspected_source="engine",
                dominant_location="front-left",
                runner_up_location="rear-right",
                supporting_window_count=5,
                supporting_sensor_count=3,
                coherent_window_count=4,
                coherence_ratio=0.8,
                location_separation_db=2.4,
                dominance_ratio=1.2,
            ),
            _spatial_summary(
                candidate_key="wheel",
                suspected_source="wheel/tire",
                dominant_location="front-left",
                runner_up_location="front-right",
                supporting_window_count=5,
                supporting_sensor_count=3,
                coherent_window_count=4,
                coherence_ratio=0.8,
                location_separation_db=2.4,
                dominance_ratio=1.2,
            ),
        ),
        findings=(wheel, driveline, engine),
        top_causes=(wheel, driveline, engine),
        expected_ranked_sources=("driveline", "engine", "wheel/tire"),
        expected_report_source="Wheel / Tire",
        expected_report_alternative="Driveline",
        expected_report_location="Front-Left",
        expected_report_frequency_fragment="12.9",
        expected_primary_ambiguous=True,
        expected_primary_suspicious=True,
        expected_primary_counterevidence_keys=("close_alternative", "incomplete_reference"),
        expected_runner_up_counterevidence_keys=("close_alternative", "incomplete_reference"),
    )
