BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"
BBFILE_COLLECTIONS += "vibesensor"
BBFILE_PATTERN_vibesensor := "^${LAYERDIR}/"
BBFILE_PRIORITY_vibesensor = "10"
LAYERSERIES_COMPAT_vibesensor = "styhead"
LAYERDEPENDS_vibesensor = "core raspberrypi"
WKS_SEARCH_PATH:append = " ${LAYERDIR}/wic"
