// Generated from vibesensor.cli.ws_schema_export
// Do not edit manually; run make sync-contracts

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** LiveWsPayload */
        LiveWsPayload: {
            /** Clients */
            clients: components["schemas"]["ClientApiRow"][];
            rotational_speeds: components["schemas"]["RotationalSpeedsPayload"] | null;
            /** Schema Version */
            schema_version: string;
            /** Selected Client Id */
            selected_client_id: string | null;
            /** Server Time */
            server_time: string;
            spectra?: components["schemas"]["SpectraPayload"];
            /** Speed Mps */
            speed_mps: number | null;
        };
        /** AlignmentInfoPayload */
        AlignmentInfoPayload: {
            /** Aligned */
            aligned: boolean;
            /** Clock Synced */
            clock_synced: boolean;
            /** Overlap Ratio */
            overlap_ratio: number;
            /** Sensor Count */
            sensor_count: number;
            /** Shared Window S */
            shared_window_s: number;
        };
        /** AxisMetrics */
        AxisMetrics: {
            /** P2P */
            p2p: number;
            /** Peaks */
            peaks: components["schemas"]["AxisPeak"][];
            /** Rms */
            rms: number;
        };
        /** AxisPeak */
        AxisPeak: {
            /** Amp */
            amp?: number;
            /** Hz */
            hz?: number;
            /** Snr Ratio */
            snr_ratio?: number;
        };
        /** ClientApiRow */
        ClientApiRow: {
            /** Connected */
            connected: boolean;
            /** Dropped Frames */
            dropped_frames: number;
            /** Firmware Version */
            firmware_version: string;
            /** Frame Samples */
            frame_samples: number;
            /** Frames Total */
            frames_total: number;
            /** Id */
            id: string;
            /** Last Reset Time */
            last_reset_time?: number | null;
            /** Last Seen Age Ms */
            last_seen_age_ms: number | null;
            latest_metrics?: components["schemas"]["ClientMetrics"];
            /** Location Code */
            location_code: string;
            /** Mac Address */
            mac_address: string;
            /** Name */
            name: string;
            /** Reset Count */
            reset_count?: number;
            /** Sample Rate Hz */
            sample_rate_hz: number;
        };
        /** ClientMetrics */
        ClientMetrics: {
            combined?: components["schemas"]["CombinedMetrics"];
            x?: components["schemas"]["AxisMetrics"];
            y?: components["schemas"]["AxisMetrics"];
            z?: components["schemas"]["AxisMetrics"];
        };
        /** CombinedMetrics */
        CombinedMetrics: {
            /** Filter Chain */
            filter_chain?: components["schemas"]["ProcessingFilterId"][];
            /** Peaks */
            peaks?: components["schemas"]["StrengthPeak"][];
            processing_profile?: components["schemas"]["ProcessingProfile"];
            strength_metrics?: components["schemas"]["VibrationStrengthMetrics"];
            /** Vib Mag P2P */
            vib_mag_p2p?: number;
            /** Vib Mag Rms */
            vib_mag_rms?: number;
            window_quality?: components["schemas"]["WindowQualityPayload"];
        };
        /** FrequencyWarningPayload */
        FrequencyWarningPayload: {
            /** Client Ids */
            client_ids: string[];
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** OrderBandPayload */
        OrderBandPayload: {
            /** Center Hz */
            center_hz: number;
            /** Key */
            key: string;
            /** Tolerance */
            tolerance: number;
        };
        /** @constant */
        ProcessingFilterId: "median_3_sample_time_domain";
        /** @enum {string} */
        ProcessingProfile: "live_display" | "diagnostic_raw" | "diagnostic_filtered";
        /** RotationalSpeedValuePayload */
        RotationalSpeedValuePayload: {
            /** Mode */
            mode: string | null;
            /** Reason */
            reason: string | null;
            /** Rpm */
            rpm: number | null;
        };
        /** RotationalSpeedsPayload */
        RotationalSpeedsPayload: {
            /** Basis Speed Source */
            basis_speed_source: string | null;
            driveshaft: components["schemas"]["RotationalSpeedValuePayload"];
            engine: components["schemas"]["RotationalSpeedValuePayload"];
            /** Order Bands */
            order_bands: components["schemas"]["OrderBandPayload"][] | null;
            wheel: components["schemas"]["RotationalSpeedValuePayload"];
        };
        /** SpectraPayload */
        SpectraPayload: {
            alignment?: components["schemas"]["AlignmentInfoPayload"];
            /** Clients */
            clients?: {
                [key: string]: components["schemas"]["SpectrumSeriesPayload"];
            };
            /** Frame Fingerprint */
            frame_fingerprint?: string;
            /** Freq */
            freq?: number[];
            warning?: components["schemas"]["FrequencyWarningPayload"];
        };
        /** SpectrumSeriesPayload */
        SpectrumSeriesPayload: {
            /** Combined Spectrum Amp G */
            combined_spectrum_amp_g?: number[];
            /** Freq */
            freq?: number[];
            strength_metrics?: components["schemas"]["VibrationStrengthMetrics"];
        };
        /** StrengthPeak */
        StrengthPeak: {
            /** Amp */
            amp: number;
            /** Hz */
            hz: number;
            /** Strength Bucket */
            strength_bucket: string | null;
            /** Vibration Strength Db */
            vibration_strength_db: number;
        };
        /** VibrationStrengthMetrics */
        VibrationStrengthMetrics: {
            /** Noise Floor Amp G */
            noise_floor_amp_g: number;
            /** Peak Amp G */
            peak_amp_g: number;
            /** Strength Bucket */
            strength_bucket: string | null;
            /** Top Peaks */
            top_peaks: components["schemas"]["StrengthPeak"][];
            /** Vibration Strength Db */
            vibration_strength_db: number;
        };
        /** WindowQualityPayload */
        WindowQualityPayload: {
            /** Clipping Axis Counts */
            clipping_axis_counts: {
                [key: string]: number;
            };
            /** Clipping Sample Count */
            clipping_sample_count: number;
            /** Clipping Sample Ratio */
            clipping_sample_ratio: number;
            /** Clipping Score */
            clipping_score: number;
            /** Context Score */
            context_score: number;
            /** Frequency Stability Score */
            frequency_stability_score: number;
            /** Mounting High Frequency Ratio */
            mounting_high_frequency_ratio: number | null;
            /** Mounting Score */
            mounting_score: number;
            /** Packet Integrity Score */
            packet_integrity_score: number;
            /** Reasons */
            reasons: string[];
            /** Sample Completeness Score */
            sample_completeness_score: number;
            /** Score */
            score: number;
            /** Shock Broadband Ratio */
            shock_broadband_ratio: number | null;
            /** Shock Crest Factor */
            shock_crest_factor: number | null;
            /** State */
            state: string;
            /** Timing Integrity Score */
            timing_integrity_score: number;
            /** Transient Score */
            transient_score: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

export const EXPECTED_SCHEMA_VERSION = "1" as const;

type WsSchema<Name extends keyof components["schemas"]> = components["schemas"][Name];

export type StrengthMetricPeak = WsSchema<"StrengthPeak">;
export type StrengthMetricsPayload = WsSchema<"VibrationStrengthMetrics">;
export type WsSpectrumSeries = WsSchema<"SpectrumSeriesPayload">;
export type WsAlignmentInfo = WsSchema<"AlignmentInfoPayload">;
export type WsFrequencyWarning = WsSchema<"FrequencyWarningPayload">;
export type WsSpectraPayload = WsSchema<"SpectraPayload">;
export type WsRotationalSpeedValue = WsSchema<"RotationalSpeedValuePayload">;
export type WsOrderBand = WsSchema<"OrderBandPayload">;
export type WsRotationalSpeeds = WsSchema<"RotationalSpeedsPayload">;
export type WsClientInfo = WsSchema<"ClientApiRow">;
export type LiveWsPayload = WsSchema<"LiveWsPayload">;
