// Generated from apps/ui/src/contracts/ws_payload_schema.json
// Do not edit manually; run tools/config/sync_shared_contracts_to_ui.mjs

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** LiveWsPayload */
    LiveWsPayload: {
      /** Clients */
      clients?: components["schemas"]["WsClientRow"][];
      rotational_speeds?: components["schemas"]["RotationalSpeedsPayload"] | null;
      /** Schema Version */
      schema_version?: string;
      /** Selected Client Id */
      selected_client_id?: string | null;
      /** Server Time */
      server_time?: string;
      spectra?: components["schemas"]["SpectraPayload"];
      /** Speed Mps */
      speed_mps?: number | null;
    };
    /** AlignmentInfoPayload */
    AlignmentInfoPayload: {
      /** Aligned */
      aligned: boolean;
      /** Clock Synced */
      clock_synced: boolean;
      /** Overlap Ratio */
      overlap_ratio: number;
      /** Sensor Count */
      sensor_count: number;
      /** Shared Window S */
      shared_window_s: number;
    };
    /** FrequencyWarningPayload */
    FrequencyWarningPayload: {
      /** Client Ids */
      client_ids: string[];
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /** OrderBandPayload */
    OrderBandPayload: {
      /** Center Hz */
      center_hz: number;
      /** Key */
      key: string;
      /** Tolerance */
      tolerance: number;
    };
    /** RotationalSpeedValuePayload */
    RotationalSpeedValuePayload: {
      /** Mode */
      mode: string | null;
      /** Reason */
      reason: string | null;
      /** Rpm */
      rpm: number | null;
    };
    /** RotationalSpeedsPayload */
    RotationalSpeedsPayload: {
      /** Basis Speed Source */
      basis_speed_source: string | null;
      driveshaft: components["schemas"]["RotationalSpeedValuePayload"];
      engine: components["schemas"]["RotationalSpeedValuePayload"];
      /** Order Bands */
      order_bands: components["schemas"]["OrderBandPayload"][] | null;
      wheel: components["schemas"]["RotationalSpeedValuePayload"];
    };
    /** SpectraPayload */
    SpectraPayload: {
      alignment?: components["schemas"]["AlignmentInfoPayload"];
      /** Clients */
      clients?: {
        [key: string]: components["schemas"]["SpectrumSeriesPayload"];
      };
      /** Freq */
      freq?: number[];
      warning?: components["schemas"]["FrequencyWarningPayload"];
    };
    /** SpectrumSeriesPayload */
    SpectrumSeriesPayload: {
      /** Combined Spectrum Amp G */
      combined_spectrum_amp_g?: number[];
      /** Freq */
      freq?: number[];
      strength_metrics?: components["schemas"]["VibrationStrengthMetrics"];
    };
    /** StrengthPeak */
    StrengthPeak: {
      /** Amp */
      amp: number;
      /** Hz */
      hz: number;
      /** Strength Bucket */
      strength_bucket: string | null;
      /** Vibration Strength Db */
      vibration_strength_db: number;
    };
    /** VibrationStrengthMetrics */
    VibrationStrengthMetrics: {
      /** Noise Floor Amp G */
      noise_floor_amp_g: number;
      /** Peak Amp G */
      peak_amp_g: number;
      /** Strength Bucket */
      strength_bucket: string | null;
      /** Top Peaks */
      top_peaks: components["schemas"]["StrengthPeak"][];
      /** Vibration Strength Db */
      vibration_strength_db: number;
    };
    /**
     * WsClientRow
     * @description Lightweight client row for WebSocket broadcast (UI-consumed fields only).
     */
    WsClientRow: {
      /** Connected */
      connected: boolean;
      /** Dropped Frames */
      dropped_frames: number;
      /** Firmware Version */
      firmware_version: string;
      /** Frames Total */
      frames_total: number;
      /** Id */
      id: string;
      /** Last Seen Age Ms */
      last_seen_age_ms: number | null;
      /** Location Code */
      location_code: string;
      /** Mac Address */
      mac_address: string;
      /** Name */
      name: string;
      /** Sample Rate Hz */
      sample_rate_hz: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;

export const EXPECTED_SCHEMA_VERSION = "1" as const;

type WsSchema<Name extends keyof components["schemas"]> = components["schemas"][Name];

export type StrengthMetricPeak = WsSchema<"StrengthPeak">;
export type StrengthMetricsPayload = WsSchema<"VibrationStrengthMetrics">;
export type WsSpectrumSeries = WsSchema<"SpectrumSeriesPayload">;
export type WsAlignmentInfo = WsSchema<"AlignmentInfoPayload">;
export type WsFrequencyWarning = WsSchema<"FrequencyWarningPayload">;
export type WsSpectraPayload = WsSchema<"SpectraPayload">;
export type WsRotationalSpeedValue = WsSchema<"RotationalSpeedValuePayload">;
export type WsOrderBand = WsSchema<"OrderBandPayload">;
export type WsRotationalSpeeds = WsSchema<"RotationalSpeedsPayload">;
export type WsClientInfo = WsSchema<"WsClientRow">;
export type LiveWsPayload = WsSchema<"LiveWsPayload">;
