// Generated from apps/ui/src/contracts/ws_payload_schema.json
// Do not edit manually; run tools/config/sync_shared_contracts_to_ui.mjs

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * LiveWsPayload
     * @description Root model for every WebSocket message pushed to the UI.
     */
    LiveWsPayload: {
      /**
       * Clients
       * @default []
       */
      clients?: components["schemas"]["ClientInfoModel"][];
      diagnostics?: components["schemas"]["DiagnosticsModel"];
      /** @default null */
      rotational_speeds?: components["schemas"]["RotationalSpeeds"] | null;
      /**
       * Schema Version
       * @default 1
       */
      schema_version?: string;
      /**
       * Selected Client Id
       * @default null
       */
      selected_client_id?: string | null;
      /** Server Time */
      server_time: string;
      /** @default null */
      spectra?: components["schemas"]["SpectraPayload"] | null;
      /**
       * Speed Mps
       * @default null
       */
      speed_mps?: number | null;
      [key: string]: unknown;
    };
    /**
     * AlignmentInfo
     * @description Multi-sensor clock-alignment quality metrics for a frequency window.
     */
    AlignmentInfo: {
      /** Aligned */
      aligned: boolean;
      /** Clock Synced */
      clock_synced: boolean;
      /** Overlap Ratio */
      overlap_ratio: number;
      /** Sensor Count */
      sensor_count: number;
      /** Shared Window S */
      shared_window_s: number;
    };
    /**
     * ClientInfoModel
     * @description Structured client row with explicit defaults for optional construction.
     */
    ClientInfoModel: {
      /**
       * Connected
       * @default false
       */
      connected?: boolean;
      /**
       * Control Addr
       * @default null
       */
      control_addr?: [string, number] | null;
      /**
       * Data Addr
       * @default null
       */
      data_addr?: [string, number] | null;
      /**
       * Dropped Frames
       * @default 0
       */
      dropped_frames?: number;
      /**
       * Duplicates Received
       * @default 0
       */
      duplicates_received?: number;
      /**
       * Firmware Version
       * @default
       */
      firmware_version?: string;
      /**
       * Frame Samples
       * @default 0
       */
      frame_samples?: number;
      /**
       * Frames Total
       * @default 0
       */
      frames_total?: number;
      /**
       * Id
       * @default
       */
      id?: string;
      /**
       * Last Ack Cmd Seq
       * @default null
       */
      last_ack_cmd_seq?: number | null;
      /**
       * Last Ack Status
       * @default null
       */
      last_ack_status?: number | null;
      /**
       * Last Reset Time
       * @default null
       */
      last_reset_time?: number | null;
      /**
       * Last Seen Age Ms
       * @default null
       */
      last_seen_age_ms?: number | null;
      /** Latest Metrics */
      latest_metrics?: {
        [key: string]: unknown;
      };
      /**
       * Location
       * @default
       */
      location?: string;
      /**
       * Mac Address
       * @default
       */
      mac_address?: string;
      /**
       * Name
       * @default
       */
      name?: string;
      /**
       * Parse Errors
       * @default 0
       */
      parse_errors?: number;
      /**
       * Queue Overflow Drops
       * @default 0
       */
      queue_overflow_drops?: number;
      /**
       * Reset Count
       * @default 0
       */
      reset_count?: number;
      /**
       * Sample Rate Hz
       * @default 0
       */
      sample_rate_hz?: number;
      /**
       * Server Queue Drops
       * @default 0
       */
      server_queue_drops?: number;
      timing_health?: components["schemas"]["TimingHealthPayload"];
    };
    /** DiagnosticEventPayload */
    DiagnosticEventPayload: {
      /** Class Key */
      class_key?: string;
      /** Event Id */
      event_id?: number;
      /** Kind */
      kind?: string;
      /** Peak Amp */
      peak_amp?: number;
      /** Peak Amp G */
      peak_amp_g?: number;
      /** Peak Hz */
      peak_hz?: number;
      /** Sensor Count */
      sensor_count?: number;
      /** Sensor Id */
      sensor_id?: string;
      /** Sensor Label */
      sensor_label?: string;
      /** Sensor Labels */
      sensor_labels?: string[];
      /** Severity Key */
      severity_key?: string | null;
      /** Vibration Strength Db */
      vibration_strength_db?: number;
    };
    /** DiagnosticLevelPayload */
    DiagnosticLevelPayload: {
      /** Agreement Count */
      agreement_count?: number;
      /** Bucket Key */
      bucket_key?: string;
      /** Class Key */
      class_key?: string;
      /** Confidence */
      confidence?: number;
      /** Peak Hz */
      peak_hz?: number;
      /** Sensor Count */
      sensor_count?: number;
      /** Sensor Label */
      sensor_label?: string;
      /** Sensor Location */
      sensor_location?: string;
      /** Strength Db */
      strength_db?: number;
    };
    /** DiagnosticsLevelsPayload */
    DiagnosticsLevelsPayload: {
      /** By Location */
      by_location: {
        [key: string]: components["schemas"]["DiagnosticLevelPayload"];
      };
      /** By Sensor */
      by_sensor: {
        [key: string]: components["schemas"]["DiagnosticLevelPayload"];
      };
      /** By Source */
      by_source: {
        [key: string]: components["schemas"]["DiagnosticLevelPayload"];
      };
    };
    /**
     * DiagnosticsModel
     * @description Structured live diagnostics payload with explicit defaults.
     */
    DiagnosticsModel: {
      /**
       * Diagnostics Sequence
       * @default 0
       */
      diagnostics_sequence?: number;
      /**
       * Driving Phase
       * @default unknown
       */
      driving_phase?: string;
      /**
       * Error
       * @default null
       */
      error?: string | null;
      /** Events */
      events?: components["schemas"]["DiagnosticEventPayload"][];
      /** Findings */
      findings?: {
          [key: string]: unknown;
        }[];
      levels?: components["schemas"]["DiagnosticsLevelsPayload"];
      /** Matrix */
      matrix?: {
        [key: string]: {
          [key: string]: components["schemas"]["MatrixCellPayload"];
        };
      };
      /** Strength Bands */
      strength_bands?: components["schemas"]["StrengthBandPayload"][];
      /**
       * Top Finding
       * @default null
       */
      top_finding?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * FrequencyWarning
     * @description Warning about frequency data quality issues in a spectra payload.
     */
    FrequencyWarning: {
      /** Client Ids */
      client_ids: string[];
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /** MatrixCellPayload */
    MatrixCellPayload: {
      /** Contributors */
      contributors: {
        [key: string]: number;
      };
      /** Count */
      count: number;
      /** Seconds */
      seconds: number;
    };
    /**
     * OrderBand
     * @description Frequency band for a specific rotation-order harmonic.
     */
    OrderBand: {
      /** Center Hz */
      center_hz: number;
      /** Key */
      key: string;
      /** Tolerance */
      tolerance: number;
    };
    /**
     * RotationalSpeedValue
     * @description Current rotational speed estimate with source and confidence metadata.
     */
    RotationalSpeedValue: {
      /**
       * Mode
       * @default null
       */
      mode?: string | null;
      /**
       * Reason
       * @default null
       */
      reason?: string | null;
      /**
       * Rpm
       * @default null
       */
      rpm?: number | null;
    };
    /**
     * RotationalSpeeds
     * @description Current per-system rotational speed estimates (wheel, driveshaft, engine).
     */
    RotationalSpeeds: {
      /**
       * Basis Speed Source
       * @default null
       */
      basis_speed_source?: string | null;
      /**
       * @default {
       *   "mode": null,
       *   "reason": null,
       *   "rpm": null
       * }
       */
      driveshaft?: components["schemas"]["RotationalSpeedValue"];
      /**
       * @default {
       *   "mode": null,
       *   "reason": null,
       *   "rpm": null
       * }
       */
      engine?: components["schemas"]["RotationalSpeedValue"];
      /**
       * Order Bands
       * @default null
       */
      order_bands?: components["schemas"]["OrderBand"][] | null;
      /**
       * @default {
       *   "mode": null,
       *   "reason": null,
       *   "rpm": null
       * }
       */
      wheel?: components["schemas"]["RotationalSpeedValue"];
    };
    /**
     * SpectraPayload
     * @description Top-level spectra block included on heavy ticks.
     */
    SpectraPayload: {
      /** @default null */
      alignment?: components["schemas"]["AlignmentInfo"] | null;
      /**
       * Clients
       * @default {}
       */
      clients?: {
        [key: string]: components["schemas"]["SpectrumSeries"];
      };
      /**
       * Freq
       * @default []
       */
      freq?: number[];
      /** @default null */
      warning?: components["schemas"]["FrequencyWarning"] | null;
      [key: string]: unknown;
    };
    /**
     * SpectrumSeries
     * @description Per-client spectrum data sent on heavy ticks.
     */
    SpectrumSeries: {
      /**
       * Combined Spectrum Amp G
       * @default []
       */
      combined_spectrum_amp_g?: number[];
      /**
       * Freq
       * @default null
       */
      freq?: number[] | null;
      strength_metrics?: components["schemas"]["StrengthMetricsModel"];
      /**
       * X
       * @default []
       */
      x?: number[];
      /**
       * Y
       * @default []
       */
      y?: number[];
      /**
       * Z
       * @default []
       */
      z?: number[];
      [key: string]: unknown;
    };
    /** StrengthBandPayload */
    StrengthBandPayload: {
      /** Key */
      key: string;
      /** Labelkey */
      labelKey: string;
      /** Max Db */
      max_db: number | null;
      /** Min Db */
      min_db: number;
    };
    /**
     * StrengthMetricsModel
     * @description Structured vibration-strength metrics with explicit defaults.
     */
    StrengthMetricsModel: {
      /** Combined Spectrum Amp G */
      combined_spectrum_amp_g?: number[];
      /**
       * Noise Floor Amp G
       * @default 0
       */
      noise_floor_amp_g?: number;
      /**
       * Peak Amp G
       * @default 0
       */
      peak_amp_g?: number;
      /**
       * Strength Bucket
       * @default null
       */
      strength_bucket?: string | null;
      /** Top Peaks */
      top_peaks?: components["schemas"]["StrengthPeak"][];
      /**
       * Vibration Strength Db
       * @default 0
       */
      vibration_strength_db?: number;
    };
    /** StrengthPeak */
    StrengthPeak: {
      /** Amp */
      amp: number;
      /** Hz */
      hz: number;
      /** Strength Bucket */
      strength_bucket: string | null;
      /** Vibration Strength Db */
      vibration_strength_db: number;
    };
    /** TimingHealthPayload */
    TimingHealthPayload: {
      /** Drift Us Total */
      drift_us_total: number;
      /** Jitter Us Ema */
      jitter_us_ema: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;

export const EXPECTED_SCHEMA_VERSION = "1" as const;

type WsSchema<Name extends keyof components["schemas"]> = components["schemas"][Name];

export type StrengthMetricPeak = WsSchema<"StrengthPeak">;
export type StrengthMetricsPayload = WsSchema<"StrengthMetricsModel">;
export type WsSpectrumSeries = WsSchema<"SpectrumSeries">;
export type WsAlignmentInfo = WsSchema<"AlignmentInfo">;
export type WsFrequencyWarning = WsSchema<"FrequencyWarning">;
export type WsSpectraPayload = WsSchema<"SpectraPayload">;
export type WsRotationalSpeedValue = WsSchema<"RotationalSpeedValue">;
export type WsOrderBand = WsSchema<"OrderBand">;
export type WsRotationalSpeeds = WsSchema<"RotationalSpeeds">;
export type WsClientInfo = WsSchema<"ClientInfoModel">;
export type WsMatrixCell = WsSchema<"MatrixCellPayload">;
export type WsDiagnosticLevel = WsSchema<"DiagnosticLevelPayload">;
export type WsDiagnosticsLevels = WsSchema<"DiagnosticsLevelsPayload">;
export type WsDiagnosticEvent = WsSchema<"DiagnosticEventPayload">;
export type WsStrengthBand = WsSchema<"StrengthBandPayload">;
export type WsDiagnosticsPayload = WsSchema<"DiagnosticsModel">;
export type LiveWsPayload = WsSchema<"LiveWsPayload">;
