"""Guards for main-release helper CLI behavior and emitted artifacts."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from urllib import error

import pytest

from tests._paths import REPO_ROOT

_MAIN_RELEASE_SCRIPT = REPO_ROOT / "tools" / "release" / "main_release.py"


def _load_main_release_module():
    spec = importlib.util.spec_from_file_location("main_release_for_tests", _MAIN_RELEASE_SCRIPT)
    assert spec is not None and spec.loader is not None, f"Unable to load {_MAIN_RELEASE_SCRIPT}"
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_compute_release_version_uses_base_date_when_no_tag_exists() -> None:
    module = _load_main_release_module()

    version_info = module.compute_release_version_info(
        REPO_ROOT,
        now=datetime(2026, 4, 6, tzinfo=UTC),
        existing_tags=[],
    )

    assert version_info == module.ReleaseVersionInfo(
        version="2026.4.6",
        tag="server-v2026.4.6",
        bundle="vibesensor-fw-v2026.4.6.zip",
    )


def test_compute_release_version_increments_latest_numeric_suffix() -> None:
    module = _load_main_release_module()

    version_info = module.compute_release_version_info(
        REPO_ROOT,
        now=datetime(2026, 4, 6, tzinfo=UTC),
        existing_tags=[
            "server-v2026.4.6",
            "server-v2026.4.6.2",
            "server-v2026.4.6.9",
            "server-v2026.4.5",
        ],
    )

    assert version_info.version == "2026.4.6.10"


def test_build_wheel_subcommand_stamps_version_and_reports_artifact(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    module = _load_main_release_module()
    repo_root = tmp_path / "repo"
    version_file = repo_root / "apps" / "server" / "vibesensor" / "_version.py"
    wheel_path = repo_root / "apps" / "server" / "dist" / "vibesensor-2026.4.6-py3-none-any.whl"
    commands: list[list[str]] = []

    def _fake_run(
        command: list[str],
        *,
        cwd: str | None = None,
        check: bool = True,
        text: bool = True,
        capture_output: bool = False,
    ) -> subprocess.CompletedProcess[str]:
        del cwd, check, text, capture_output
        command_list = [str(part) for part in command]
        commands.append(command_list)
        if command_list[:3] == ["/fake/python", "-m", "build"] and "--wheel" in command_list:
            wheel_path.parent.mkdir(parents=True, exist_ok=True)
            wheel_path.write_text("wheel", encoding="utf-8")
        return subprocess.CompletedProcess(command_list, 0, stdout="", stderr="")

    monkeypatch.setattr(module.subprocess, "run", _fake_run)
    monkeypatch.setattr(module.sys, "executable", "/fake/python")

    assert (
        module.main(
            [
                "build-wheel",
                "--repo-root",
                str(repo_root),
                "--version",
                "2026.4.6",
            ]
        )
        == 0
    )

    assert version_file.read_text(encoding="utf-8") == (
        '# Auto-generated by main-release workflow - do not edit.\n__version__ = "2026.4.6"\n'
    )
    assert capsys.readouterr().out.strip() == str(wheel_path)
    assert any(command[:4] == ["/fake/python", "-m", "pip", "install"] for command in commands)
    assert any(
        command[:3] == ["/fake/python", "-m", "build"] and "--wheel" in command
        for command in commands
    )


def test_generate_firmware_manifest_subcommand_writes_manifest_and_reports_path(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    module = _load_main_release_module()
    firmware_dir = tmp_path / "firmware"
    env_dir = firmware_dir / "dist" / "esp32dev"
    env_dir.mkdir(parents=True)
    firmware_bin = env_dir / "firmware.bin"
    firmware_bin.write_bytes(b"firmware")
    bootloader_bin = env_dir / "bootloader.bin"
    bootloader_bin.write_bytes(b"boot")
    commands: list[list[str]] = []

    def _fake_run(
        command: list[str],
        *,
        cwd: str | None = None,
        check: bool = True,
        text: bool = True,
        capture_output: bool = False,
    ) -> subprocess.CompletedProcess[str]:
        del cwd, check, text, capture_output
        command_list = [str(part) for part in command]
        commands.append(command_list)
        if command_list[:3] == ["pio", "run", "-e"] and "envdump" in command_list:
            return subprocess.CompletedProcess(
                command_list,
                0,
                stdout="ESP32_APP_OFFSET=0x20000\n",
                stderr="",
            )
        return subprocess.CompletedProcess(command_list, 0, stdout="", stderr="")

    monkeypatch.setattr(module.subprocess, "run", _fake_run)

    assert (
        module.main(
            [
                "generate-firmware-manifest",
                "--firmware-dir",
                str(firmware_dir),
                "--generated-from",
                "deadbeef",
            ]
        )
        == 0
    )

    manifest_path = firmware_dir / "dist" / "flash.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert capsys.readouterr().out.strip() == str(manifest_path)
    assert manifest == {
        "generated_from": "deadbeef",
        "environments": [
            {
                "name": "esp32dev",
                "segments": [
                    {
                        "file": "esp32dev/firmware.bin",
                        "offset": "0x20000",
                        "sha256": hashlib.sha256(b"firmware").hexdigest(),
                    },
                    {
                        "file": "esp32dev/bootloader.bin",
                        "offset": "0x1000",
                        "sha256": hashlib.sha256(b"boot").hexdigest(),
                    },
                ],
            },
        ],
    }
    assert any(command[:3] == ["pio", "run", "-e"] and "envdump" in command for command in commands)


def test_cleanup_releases_dry_run_prints_selected_wheel_esp_releases(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    module = _load_main_release_module()
    releases = [
        {"id": 1, "tag_name": "server-v2026.4.6", "name": "Wheel / ESP release 2026.4.6"},
        {"id": 2, "tag_name": "server-v2026.4.5", "name": "Wheel / ESP release 2026.4.5"},
        {"id": 3, "tag_name": "server-v2026.4.4", "name": "Release 2026.4.4"},
        {"id": 4, "tag_name": "weekly-v2026.4.5", "name": "Weekly image"},
    ]

    monkeypatch.setattr(
        module,
        "_github_request",
        lambda method, repo, path: releases if method == "GET" else None,
    )

    assert (
        module.main(
            [
                "cleanup-releases",
                "--repo",
                "Skamba/VibeSensor",
                "--current-tag",
                "server-v2026.4.6",
                "--dry-run",
            ]
        )
        == 0
    )

    assert json.loads(capsys.readouterr().out) == [
        {
            "id": 2,
            "tag": "server-v2026.4.5",
            "title": "Wheel / ESP release 2026.4.5",
        }
    ]


def test_cleanup_releases_reports_missing_tag_and_continues(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    module = _load_main_release_module()
    deleted_paths: list[str] = []
    releases = [
        {"id": 1, "tag_name": "server-v2026.4.6", "name": "Wheel / ESP release 2026.4.6"},
        {"id": 2, "tag_name": "server-v2026.4.5", "name": "Wheel / ESP release 2026.4.5"},
        {"id": 3, "tag_name": "server-v2026.4.4", "name": "Release 2026.4.4"},
    ]

    def _fake_github_request(method: str, repo: str, path: str):
        del repo
        if method == "GET":
            return releases
        deleted_paths.append(path)
        if path == "git/refs/tags/server-v2026.4.5":
            raise error.HTTPError("https://example.invalid", 404, "missing", None, None)
        return None

    monkeypatch.setattr(module, "_github_request", _fake_github_request)

    assert (
        module.main(
            [
                "cleanup-releases",
                "--repo",
                "Skamba/VibeSensor",
                "--current-tag",
                "server-v2026.4.6",
            ]
        )
        == 0
    )

    output = capsys.readouterr().out
    assert "Deleting superseded Wheel / ESP release server-v2026.4.5" in output
    assert "Tag server-v2026.4.5 was already absent" in output
    assert set(deleted_paths) == {"releases/2", "git/refs/tags/server-v2026.4.5"}
