"""Guards for the extracted main-release helper scripts."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from urllib import error

from tests._paths import REPO_ROOT

_MAIN_RELEASE_SCRIPT = REPO_ROOT / "tools" / "release" / "main_release.py"


def _load_main_release_module():
    spec = importlib.util.spec_from_file_location("main_release_for_tests", _MAIN_RELEASE_SCRIPT)
    assert spec is not None and spec.loader is not None, f"Unable to load {_MAIN_RELEASE_SCRIPT}"
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_compute_release_version_uses_base_date_when_no_tag_exists() -> None:
    module = _load_main_release_module()

    version_info = module.compute_release_version_info(
        REPO_ROOT,
        now=datetime(2026, 4, 6, tzinfo=UTC),
        existing_tags=[],
    )

    assert version_info == module.ReleaseVersionInfo(
        version="2026.4.6",
        tag="server-v2026.4.6",
        bundle="vibesensor-fw-v2026.4.6.zip",
    )


def test_compute_release_version_increments_latest_numeric_suffix() -> None:
    module = _load_main_release_module()

    version_info = module.compute_release_version_info(
        REPO_ROOT,
        now=datetime(2026, 4, 6, tzinfo=UTC),
        existing_tags=[
            "server-v2026.4.6",
            "server-v2026.4.6.2",
            "server-v2026.4.6.9",
            "server-v2026.4.5",
        ],
    )

    assert version_info.version == "2026.4.6.10"


def test_build_server_wheel_stamps_version_before_running_build(
    monkeypatch,
    tmp_path: Path,
) -> None:
    module = _load_main_release_module()
    repo_root = tmp_path / "repo"
    version_file = repo_root / "apps" / "server" / "vibesensor" / "_version.py"
    version_file.parent.mkdir(parents=True, exist_ok=True)
    commands: list[tuple[list[str], Path | None, bool]] = []

    def _fake_run(command: list[str], *, cwd: Path | None = None, capture_output: bool = False):
        commands.append((list(command), cwd, capture_output))
        if command[1:4] == ["-m", "build", "--wheel"]:
            wheel_path = (
                repo_root / "apps" / "server" / "dist" / "vibesensor-2026.4.6-py3-none-any.whl"
            )
            wheel_path.parent.mkdir(parents=True, exist_ok=True)
            wheel_path.write_text("wheel", encoding="utf-8")
        return subprocess.CompletedProcess(command, 0, stdout="", stderr="")

    monkeypatch.setattr(module, "_run", _fake_run)
    monkeypatch.setattr(module.sys, "executable", "/fake/python")

    wheel_path = module.build_server_wheel(repo_root, "2026.4.6")

    assert version_file.read_text(encoding="utf-8") == (
        '# Auto-generated by main-release workflow - do not edit.\n__version__ = "2026.4.6"\n'
    )
    assert wheel_path.name == "vibesensor-2026.4.6-py3-none-any.whl"
    assert commands == [
        (
            ["/fake/python", "-m", "pip", "install", "--upgrade", "pip", "build"],
            repo_root,
            False,
        ),
        (["/fake/python", "-m", "build", "--wheel", "apps/server/"], repo_root, False),
    ]


def test_write_firmware_manifest_uses_envdump_offsets(monkeypatch, tmp_path: Path) -> None:
    module = _load_main_release_module()
    firmware_dir = tmp_path / "firmware"
    env_dir = firmware_dir / "dist" / "esp32dev"
    env_dir.mkdir(parents=True)
    firmware_bin = env_dir / "firmware.bin"
    firmware_bin.write_bytes(b"firmware")
    bootloader_bin = env_dir / "bootloader.bin"
    bootloader_bin.write_bytes(b"boot")

    monkeypatch.setattr(
        module,
        "_run",
        lambda command, *, cwd=None, capture_output=False: subprocess.CompletedProcess(
            command,
            0,
            stdout="ESP32_APP_OFFSET=0x20000\n",
            stderr="",
        ),
    )

    manifest_path = module.write_firmware_manifest(firmware_dir, generated_from="deadbeef")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    assert manifest == {
        "generated_from": "deadbeef",
        "environments": [
            {
                "name": "esp32dev",
                "segments": [
                    {
                        "file": "esp32dev/firmware.bin",
                        "offset": "0x20000",
                        "sha256": hashlib.sha256(b"firmware").hexdigest(),
                    },
                    {
                        "file": "esp32dev/bootloader.bin",
                        "offset": "0x1000",
                        "sha256": hashlib.sha256(b"boot").hexdigest(),
                    },
                ],
            },
        ],
    }


def test_cleanup_superseded_releases_keeps_current_and_ignores_missing_tags(monkeypatch) -> None:
    module = _load_main_release_module()
    calls: list[tuple[str, str, str]] = []
    releases = [
        {"id": 1, "tag_name": "server-v2026.4.6", "name": "Wheel / ESP release 2026.4.6"},
        {"id": 2, "tag_name": "server-v2026.4.5", "name": "Wheel / ESP release 2026.4.5"},
        {"id": 3, "tag_name": "server-v2026.4.4", "name": "Release 2026.4.4"},
        {"id": 4, "tag_name": "weekly-v2026.4.5", "name": "Weekly image"},
    ]

    def _fake_github_request(method: str, repo: str, path: str):
        calls.append((method, repo, path))
        if method == "GET":
            return releases
        if path == "git/refs/tags/server-v2026.4.5":
            raise error.HTTPError("https://example.invalid", 404, "missing", None, None)
        return None

    monkeypatch.setattr(module, "_github_request", _fake_github_request)

    removed = module.cleanup_superseded_releases(
        "Skamba/VibeSensor",
        current_tag="server-v2026.4.6",
        release_title_prefix="Wheel / ESP release",
    )

    assert removed == [
        module.ReleaseSummary(id=2, tag="server-v2026.4.5", title="Wheel / ESP release 2026.4.5"),
    ]
    assert calls == [
        ("GET", "Skamba/VibeSensor", "releases?per_page=100&page=1"),
        ("DELETE", "Skamba/VibeSensor", "releases/2"),
        ("DELETE", "Skamba/VibeSensor", "git/refs/tags/server-v2026.4.5"),
    ]
