"""Guards for main-release helper CLI behavior and emitted artifacts."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import subprocess
import sys
import tarfile
import zipfile
from datetime import UTC, datetime
from pathlib import Path
from urllib import error

import pytest

from tests._paths import REPO_ROOT

_MAIN_RELEASE_SCRIPT = REPO_ROOT / "tools" / "release" / "main_release.py"


def _load_main_release_module():
    spec = importlib.util.spec_from_file_location("main_release_for_tests", _MAIN_RELEASE_SCRIPT)
    assert spec is not None and spec.loader is not None, f"Unable to load {_MAIN_RELEASE_SCRIPT}"
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_compute_release_version_uses_base_date_when_no_tag_exists() -> None:
    module = _load_main_release_module()

    version_info = module.compute_release_version_info(
        REPO_ROOT,
        now=datetime(2026, 4, 6, tzinfo=UTC),
        existing_tags=[],
    )

    assert version_info == module.ReleaseVersionInfo(
        version="2026.4.6",
        tag="server-v2026.4.6",
        bundle="vibesensor-fw-v2026.4.6.zip",
    )


def test_compute_release_version_increments_latest_numeric_suffix() -> None:
    module = _load_main_release_module()

    version_info = module.compute_release_version_info(
        REPO_ROOT,
        now=datetime(2026, 4, 6, tzinfo=UTC),
        existing_tags=[
            "server-v2026.4.6",
            "server-v2026.4.6.2",
            "server-v2026.4.6.9",
            "server-v2026.4.5",
        ],
    )

    assert version_info.version == "2026.4.6.10"
    assert version_info.tag == "server-v2026.4.6.10"
    assert version_info.bundle == "vibesensor-fw-v2026.4.6.10.zip"


def test_build_wheel_subcommand_stamps_version_and_reports_artifact(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    module = _load_main_release_module()
    repo_root = tmp_path / "repo"
    version_file = repo_root / "apps" / "server" / "vibesensor" / "_version.py"
    wheel_path = repo_root / "apps" / "server" / "dist" / "vibesensor-2026.4.6-py3-none-any.whl"
    commands: list[list[str]] = []

    def _fake_run(
        command: list[str],
        *,
        cwd: str | None = None,
        check: bool = True,
        text: bool = True,
        capture_output: bool = False,
    ) -> subprocess.CompletedProcess[str]:
        del cwd, check, text, capture_output
        command_list = [str(part) for part in command]
        commands.append(command_list)
        if command_list[:3] == ["/fake/python", "-m", "build"] and "--wheel" in command_list:
            wheel_path.parent.mkdir(parents=True, exist_ok=True)
            wheel_path.write_text("wheel", encoding="utf-8")
        stdout = "0123abcd\n" if command_list == ["git", "rev-parse", "HEAD"] else ""
        return subprocess.CompletedProcess(command_list, 0, stdout=stdout, stderr="")

    monkeypatch.setattr(module.subprocess, "run", _fake_run)
    monkeypatch.setattr(module.sys, "executable", "/fake/python")

    assert (
        module.main(
            [
                "build-wheel",
                "--repo-root",
                str(repo_root),
                "--version",
                "2026.4.6",
            ]
        )
        == 0
    )

    assert version_file.read_text(encoding="utf-8") == (
        "# Auto-generated by main-release workflow - do not edit.\n"
        '__version__ = "2026.4.6"\n'
        '__commit__ = "0123abcd"\n'
    )
    assert capsys.readouterr().out.strip() == str(wheel_path)
    assert any(command[:4] == ["/fake/python", "-m", "pip", "install"] for command in commands)
    assert any(
        command[:3] == ["/fake/python", "-m", "build"] and "--wheel" in command
        for command in commands
    )
    pip_index = next(
        index
        for index, command in enumerate(commands)
        if command[:4] == ["/fake/python", "-m", "pip", "install"]
    )
    build_index = next(
        index
        for index, command in enumerate(commands)
        if command[:3] == ["/fake/python", "-m", "build"]
    )
    assert pip_index < build_index


def test_build_wheelhouse_downloads_pi_binaries_and_proves_an_offline_install(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    module = _load_main_release_module()
    wheel_path = tmp_path / "dist" / "vibesensor-2026.4.6-py3-none-any.whl"
    wheel_path.parent.mkdir()
    wheel_path.write_text("wheel", encoding="utf-8")
    commands: list[list[str]] = []

    def _fake_run(command: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        command_list = [str(part) for part in command]
        commands.append(command_list)
        if command_list[3] == "download":
            dest = Path(command_list[command_list.index("--dest") + 1])
            dest.mkdir(parents=True)
            for name in (wheel_path.name, "numpy-2.5.3-cp313-cp313-linux_armv7l.whl"):
                (dest / name).write_text(name, encoding="utf-8")
        return subprocess.CompletedProcess(command_list, 0, stdout="", stderr="")

    monkeypatch.setattr(module.subprocess, "run", _fake_run)
    monkeypatch.setattr(module.sys, "executable", "/fake/python")

    assert (
        module.main(
            [
                "build-wheelhouse",
                "--wheel-path",
                str(wheel_path),
                "--version",
                "2026.4.6",
                "--output-dir",
                str(tmp_path / "out"),
                "--machine",
                "armv7l",
            ]
        )
        == 0
    )

    output = tmp_path / "out" / "vibesensor-wheelhouse-2026.4.6-cp313-linux_armv7l.tar"
    assert capsys.readouterr().out.strip() == str(output)
    download, dry_run = commands
    assert download[:4] == ["/fake/python", "-m", "pip", "download"]
    assert dry_run[:4] == ["/fake/python", "-m", "pip", "install"]
    for command in (download, dry_run):
        assert "--only-binary=:all:" in command
        assert command[command.index("--python-version") + 1] == "3.13"
        assert "linux_armv7l" in command
        assert command[-1] == f"{wheel_path.resolve()}[esp]"
    assert "https://www.piwheels.org/simple" in download
    assert {"--dry-run", "--no-index"} <= set(dry_run)
    with tarfile.open(output) as tar:
        assert tar.getnames() == ["numpy-2.5.3-cp313-cp313-linux_armv7l.whl"]


def test_build_wheelhouse_for_arm64_builds_pure_sdists_and_uses_pypi_aarch64_wheels(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    module = _load_main_release_module()
    wheel_path = tmp_path / "dist" / "vibesensor-2026.4.6-py3-none-any.whl"
    wheel_path.parent.mkdir()
    with zipfile.ZipFile(wheel_path, "w") as wheel:
        wheel.writestr(
            "vibesensor-2026.4.6.dist-info/METADATA",
            "Name: vibesensor\n"
            "Requires-Dist: numpy<3,>=2.4.4\n"
            'Requires-Dist: esptool<6,>=5.2.0; extra == "esp"\n',
        )
    numpy = "numpy-2.5.3-cp313-cp313-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl"
    commands: list[list[str]] = []

    def _fake_run(command: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        command_list = [str(part) for part in command]
        commands.append(command_list)
        if command_list[3] == "wheel":
            wheel_dir = Path(command_list[command_list.index("--wheel-dir") + 1])
            (wheel_dir / "esptool-5.5.0-py3-none-any.whl").write_text("e", encoding="utf-8")
        if command_list[3] == "download":
            dest = Path(command_list[command_list.index("--dest") + 1])
            (dest / numpy).write_text("n", encoding="utf-8")
        return subprocess.CompletedProcess(command_list, 0, stdout="", stderr="")

    monkeypatch.setattr(module.subprocess, "run", _fake_run)
    monkeypatch.setattr(module.sys, "executable", "/fake/python")

    args = ["build-wheelhouse", "--wheel-path", str(wheel_path), "--version", "2026.4.6"]
    out_dir = tmp_path / "out"
    assert module.main([*args, "--output-dir", str(out_dir), "--machine", "aarch64"]) == 0

    # Updaters before arm64 support take the first vibesensor-wheelhouse-*.tar asset.
    output = out_dir / "vibesensor-arm64-wheelhouse-2026.4.6-cp313-linux_aarch64.tar"
    assert capsys.readouterr().out.strip() == str(output)
    build, download, dry_run = commands
    assert build[3:5] == ["wheel", "--no-deps"]
    assert build[-1] == "esptool<6,>=5.2.0"
    assert "https://www.piwheels.org/simple" not in download
    for command in (download, dry_run):
        assert "linux_aarch64" in command
        assert "manylinux_2_28_aarch64" in command
        assert not any("armv7l" in part for part in command)
    with tarfile.open(output) as tar:
        assert tar.getnames() == ["esptool-5.5.0-py3-none-any.whl", numpy]


def _partition_entry(subtype: int, offset: int, size: int, label: bytes) -> bytes:
    return (
        b"\xaa\x50"
        + bytes([0x00, subtype])
        + offset.to_bytes(4, "little")
        + size.to_bytes(4, "little")
        + label.ljust(16, b"\x00")
        + bytes(4)
    )


_FIRMWARE_VERSION = "fw-20261005.1200+0123456789ab"


def _app_image(chip_id: int, *, version_stamp: bytes | None = None) -> bytes:
    """An ESP app image: magic byte, the chip ID in the extended header, and the
    version the firmware reports after its marker (runtime_config.h)."""
    stamp = (
        b"VIBESENSOR_FIRMWARE_VERSION=" + _FIRMWARE_VERSION.encode() + b"\0"
        if version_stamp is None
        else version_stamp
    )
    return bytes([0xE9]) + bytes(11) + chip_id.to_bytes(2, "little") + b"app\0" + stamp


def _write_env_dist(dist_dir: Path, env_name: str, firmware: bytes, partitions: bytes) -> None:
    env_dir = dist_dir / env_name
    env_dir.mkdir(parents=True)
    (env_dir / "firmware.bin").write_bytes(firmware)
    (env_dir / "bootloader.bin").write_bytes(b"boot-" + env_name.encode())
    (env_dir / "partitions.bin").write_bytes(partitions)


def _fake_platformio_metadata(
    monkeypatch: pytest.MonkeyPatch, module, flash_images: dict[str, list[dict[str, str]]]
) -> list[list[str]]:
    commands: list[list[str]] = []

    def _fake_run(command: list[str], **_kwargs) -> subprocess.CompletedProcess[str]:
        commands.append(command)
        assert command[:3] == ["pio", "project", "metadata"]
        envs = [command[i + 1] for i, arg in enumerate(command) if arg == "--environment"]
        payload = {env: {"extra": {"flash_images": flash_images[env]}} for env in envs}
        return subprocess.CompletedProcess(command, 0, stdout=json.dumps(payload), stderr="")

    monkeypatch.setattr(module.subprocess, "run", _fake_run)
    return commands


def test_generate_firmware_manifest_takes_chip_and_offsets_from_each_build(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    module = _load_main_release_module()
    firmware_dir = tmp_path / "firmware"
    dist_dir = firmware_dir / "dist"
    atom_firmware = _app_image(0)  # ESP32
    c3_firmware = _app_image(5)  # ESP32-C3
    factory = _partition_entry(0x00, 0x10000, 0x140000, b"factory").ljust(3072, b"\xff")
    # OTA layout without a factory app: the bootloader starts ota_0 on a fresh flash.
    ota = (
        _partition_entry(0x10, 0x20000, 0x140000, b"app0")
        + _partition_entry(0x11, 0x160000, 0x140000, b"app1")
    ).ljust(3072, b"\xff")
    _write_env_dist(dist_dir, "m5stack_atom", atom_firmware, factory)
    _write_env_dist(dist_dir, "esp32-c3-devkitm-1", c3_firmware, ota)

    def _images(env: str, bootloader_offset: str) -> list[dict[str, str]]:
        build = f"/build/.pio/build/{env}"
        return [
            {"offset": bootloader_offset, "path": f"{build}/bootloader.bin"},
            {"offset": "0x8000", "path": f"{build}/partitions.bin"},
            {"offset": "0xe000", "path": "/framework/tools/partitions/boot_app0.bin"},
        ]

    commands = _fake_platformio_metadata(
        monkeypatch,
        module,
        {
            "m5stack_atom": _images("m5stack_atom", "0x1000"),
            "esp32-c3-devkitm-1": _images("esp32-c3-devkitm-1", "0x0000"),
        },
    )

    assert (
        module.main(
            [
                "generate-firmware-manifest",
                "--firmware-dir",
                str(firmware_dir),
                "--generated-from",
                "deadbeef",
            ]
        )
        == 0
    )

    manifest_path = dist_dir / "flash.json"
    assert capsys.readouterr().out.strip() == str(manifest_path)
    assert commands == [
        [
            "pio",
            "project",
            "metadata",
            "--project-dir",
            str(firmware_dir),
            "--environment",
            "esp32-c3-devkitm-1",
            "--environment",
            "m5stack_atom",
            "--json-output",
        ]
    ]

    def _segment(env: str, name: str, offset: str, content: bytes) -> dict[str, str]:
        return {
            "file": f"{env}/{name}",
            "offset": offset,
            "sha256": hashlib.sha256(content).hexdigest(),
        }

    c3 = "esp32-c3-devkitm-1"
    atom = "m5stack_atom"
    assert json.loads(manifest_path.read_text(encoding="utf-8")) == {
        "generated_from": "deadbeef",
        "environments": [
            {
                "name": c3,
                "chip": "esp32c3",
                "firmware_version": _FIRMWARE_VERSION,
                "segments": [
                    _segment(c3, "bootloader.bin", "0x0000", b"boot-" + c3.encode()),
                    _segment(c3, "partitions.bin", "0x8000", ota),
                    _segment(c3, "firmware.bin", "0x20000", c3_firmware),
                ],
            },
            {
                "name": atom,
                "chip": "esp32",
                "firmware_version": _FIRMWARE_VERSION,
                "segments": [
                    _segment(atom, "bootloader.bin", "0x1000", b"boot-" + atom.encode()),
                    _segment(atom, "partitions.bin", "0x8000", factory),
                    _segment(atom, "firmware.bin", "0x10000", atom_firmware),
                ],
            },
        ],
    }


def test_generate_firmware_manifest_refuses_an_image_without_a_version_stamp(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    module = _load_main_release_module()
    firmware_dir = tmp_path / "firmware"
    _write_env_dist(
        firmware_dir / "dist", "m5stack_atom", _app_image(0, version_stamp=b"esp32-atom-0.1\0"), b""
    )
    _fake_platformio_metadata(
        monkeypatch,
        module,
        {
            "m5stack_atom": [
                {"offset": "0x1000", "path": "/build/bootloader.bin"},
                {"offset": "0x8000", "path": "/build/partitions.bin"},
            ]
        },
    )

    with pytest.raises(SystemExit, match=r"carries no firmware version stamp"):
        module.main(["generate-firmware-manifest", "--firmware-dir", str(firmware_dir)])


def test_generate_firmware_manifest_refuses_an_image_the_build_does_not_place(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    module = _load_main_release_module()
    firmware_dir = tmp_path / "firmware"
    _write_env_dist(firmware_dir / "dist", "m5stack_atom", _app_image(0), b"")
    _fake_platformio_metadata(
        monkeypatch,
        module,
        {"m5stack_atom": [{"offset": "0x8000", "path": "/build/partitions.bin"}]},
    )

    with pytest.raises(SystemExit, match=r"m5stack_atom/bootloader.bin has no flash offset"):
        module.main(["generate-firmware-manifest", "--firmware-dir", str(firmware_dir)])

    assert not (firmware_dir / "dist" / "flash.json").exists()


def test_cleanup_releases_dry_run_prints_selected_wheel_esp_releases(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    module = _load_main_release_module()
    releases = [
        {"id": 1, "tag_name": "server-v2026.4.6", "name": "Wheel / ESP release 2026.4.6"},
        {"id": 2, "tag_name": "server-v2026.4.5", "name": "Wheel / ESP release 2026.4.5"},
        {"id": 3, "tag_name": "server-v2026.4.4", "name": "Release 2026.4.4"},
        {"id": 4, "tag_name": "weekly-v2026.4.5", "name": "Weekly image"},
    ]

    monkeypatch.setattr(
        module,
        "_github_request",
        lambda method, repo, path: releases if method == "GET" else None,
    )

    assert (
        module.main(
            [
                "cleanup-releases",
                "--repo",
                "Skamba/VibeSensor",
                "--current-tag",
                "server-v2026.4.6",
                "--dry-run",
            ]
        )
        == 0
    )

    assert json.loads(capsys.readouterr().out) == [
        {
            "id": 2,
            "tag": "server-v2026.4.5",
            "title": "Wheel / ESP release 2026.4.5",
        }
    ]


def test_cleanup_releases_reports_missing_tag_and_continues(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    module = _load_main_release_module()
    deleted_paths: list[str] = []
    releases = [
        {"id": 1, "tag_name": "server-v2026.4.6", "name": "Wheel / ESP release 2026.4.6"},
        {"id": 2, "tag_name": "server-v2026.4.5", "name": "Wheel / ESP release 2026.4.5"},
        {"id": 3, "tag_name": "server-v2026.4.4", "name": "Release 2026.4.4"},
    ]

    def _fake_github_request(method: str, repo: str, path: str):
        del repo
        if method == "GET":
            return releases
        deleted_paths.append(path)
        if path == "git/refs/tags/server-v2026.4.5":
            raise error.HTTPError("https://example.invalid", 404, "missing", None, None)
        return None

    monkeypatch.setattr(module, "_github_request", _fake_github_request)

    assert (
        module.main(
            [
                "cleanup-releases",
                "--repo",
                "Skamba/VibeSensor",
                "--current-tag",
                "server-v2026.4.6",
            ]
        )
        == 0
    )

    output = capsys.readouterr().out
    assert "Deleting superseded Wheel / ESP release server-v2026.4.5" in output
    assert "Tag server-v2026.4.5 was already absent" in output
    assert "server-v2026.4.6" not in deleted_paths
    assert set(deleted_paths) == {"releases/2", "git/refs/tags/server-v2026.4.5"}


def test_github_request_uses_timeout_and_returns_json(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = _load_main_release_module()
    captured: dict[str, object] = {}

    class _FakeResponse:
        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc, traceback):
            return False

        def read(self) -> bytes:
            return b'{"ok": true}'

    def _fake_urlopen(req, *, timeout):  # type: ignore[no-untyped-def]
        captured["method"] = req.get_method()
        captured["url"] = req.full_url
        captured["timeout"] = timeout
        return _FakeResponse()

    monkeypatch.setenv("GITHUB_TOKEN", "token")
    monkeypatch.setattr(module.request, "urlopen", _fake_urlopen)

    assert module._github_request("GET", "Skamba/VibeSensor", "releases") == {"ok": True}
    assert captured == {
        "method": "GET",
        "url": "https://api.github.com/repos/Skamba/VibeSensor/releases",
        "timeout": module.GITHUB_API_TIMEOUT_S,
    }
    assert captured["url"].endswith("/releases")


def test_github_request_reports_url_errors_with_method_and_path(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = _load_main_release_module()

    def _raise_url_error(req, *, timeout):  # type: ignore[no-untyped-def]
        del req, timeout
        raise error.URLError("network unavailable")

    monkeypatch.setenv("GITHUB_TOKEN", "token")
    monkeypatch.setattr(module.request, "urlopen", _raise_url_error)

    with pytest.raises(SystemExit) as exc_info:
        module._github_request("GET", "Skamba/VibeSensor", "releases")

    assert str(exc_info.value) == (
        "GitHub API GET /repos/Skamba/VibeSensor/releases failed: network unavailable"
    )


def test_github_request_reports_timeouts_with_method_path_and_limit(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = _load_main_release_module()

    def _raise_timeout(req, *, timeout):  # type: ignore[no-untyped-def]
        del req, timeout
        raise TimeoutError("timed out")

    monkeypatch.setenv("GITHUB_TOKEN", "token")
    monkeypatch.setattr(module.request, "urlopen", _raise_timeout)

    with pytest.raises(SystemExit) as exc_info:
        module._github_request(
            "DELETE",
            "Skamba/VibeSensor",
            "git/refs/tags/server-v2026.4.5",
        )

    assert str(exc_info.value) == (
        "GitHub API DELETE "
        "/repos/Skamba/VibeSensor/git/refs/tags/server-v2026.4.5 "
        "timed out after 30s."
    )


def test_github_request_preserves_http_errors_for_delete_404_tolerance(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = _load_main_release_module()
    http_error = error.HTTPError("https://example.invalid", 404, "missing", None, None)

    def _raise_http_error(req, *, timeout):  # type: ignore[no-untyped-def]
        del req, timeout
        raise http_error

    monkeypatch.setenv("GITHUB_TOKEN", "token")
    monkeypatch.setattr(module.request, "urlopen", _raise_http_error)

    with pytest.raises(error.HTTPError) as exc_info:
        module._github_request(
            "DELETE",
            "Skamba/VibeSensor",
            "git/refs/tags/server-v2026.4.5",
        )

    assert exc_info.value is http_error
